#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent


rdb = agent.redis_connect(privileged=False)

subscription = rdb.hgetall('cluster/subscription')

# Check if the subscription hash table exists
if subscription:
    # Get the subscription secret
    agent.set_env("SUBSCRIPTION_SECRET", subscription['auth_token'])
    # Get subscription ID
    agent.set_env("SUBSCRIPTION_SYSTEMID", subscription['system_id'])
