#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json

import agent
import agent.tasks

data = json.load(sys.stdin)
lets_encrypt = data.get("lets_encrypt", 'false')

agent.set_env('TRAEFIK_LETS_ENCRYPT', lets_encrypt)

# Find default traefik instance for current node
default_traefik_id = agent.resolve_agent_id('traefik@node')
if default_traefik_id is None:
    sys.exit(2)

# Configure Traefik to route "/"
response = agent.tasks.run(
    agent_id=agent.resolve_agent_id('traefik@node'),
    action='set-route',
    data={
        'instance': os.environ['MODULE_ID'] + '-wizard',
        'url':  'http://127.0.0.1:' + os.environ["APACHE_PORT"] + '/',
        'http2https':  os.environ["TRAEFIK_HTTP2HTTPS"] == "true",
        'lets_encrypt': lets_encrypt,
        'host': os.environ["NETHVOICE_HOST"]
    },
)

# Check if traefik configuration has been successfull
agent.assert_exp(response['exit_code'] == 0)

# Configure Traefik to route "/tancredi" path requests to the webapp service
response = agent.tasks.run(
    agent_id=agent.resolve_agent_id('traefik@node'),
    action='set-route',
    data={
        'instance': os.environ['MODULE_ID'] + '-tancredi',
        'url':  'http://127.0.0.1:' + os.environ["TANCREDIPORT"] + '/tancredi',
        'http2https':  False,
        'lets_encrypt': lets_encrypt,
        'host': os.environ["NETHVOICE_HOST"],
        'path': '/tancredi',
    },
)

# Check if traefik configuration has been successfull
agent.assert_exp(response['exit_code'] == 0)

# Configure Traefik to route "/provisioning" path requests to get phones configuration
response = agent.tasks.run(
    agent_id=agent.resolve_agent_id('traefik@node'),
    action='set-route',
    data={
        'instance': os.environ['MODULE_ID'] + '-provisioning',
        'url':  'http://127.0.0.1:' + os.environ["TANCREDIPORT"] + '/provisioning',
        'http2https':  False,
        'lets_encrypt': lets_encrypt,
        'host': os.environ["NETHVOICE_HOST"],
        'path': '/provisioning',
    },
)

# Check if traefik configuration has been successfull
agent.assert_exp(response['exit_code'] == 0)

response = agent.tasks.run(
    agent_id=agent.resolve_agent_id('traefik@node'),
    action='set-route',
    data={
        'instance': os.environ['MODULE_ID'] + '-ui',
        'url':  'http://127.0.0.1:' + os.environ["NETHCTI_UI_PORT"],
        'http2https':  os.environ["TRAEFIK_HTTP2HTTPS"] == "true",
        'lets_encrypt': lets_encrypt,
        'host': os.environ["NETHCTI_UI_HOST"],
    },
)

# Check if traefik configuration has been successfull
agent.assert_exp(response['exit_code'] == 0)

## Set up NethCTI-Server to allow https and websocket connections on same host
response = agent.tasks.run(
    agent_id=agent.resolve_agent_id('traefik@node'),
    action='set-route',
    data={
        'instance': os.environ['MODULE_ID'] + '-server-api',
        'url':  'http://127.0.0.1:' + os.environ["NETHCTI_SERVER_API_PORT"],
        'http2https':  os.environ["TRAEFIK_HTTP2HTTPS"] == "true",
        'lets_encrypt': lets_encrypt,
        'host': os.environ["NETHVOICE_HOST"],
        'path': '/webrest',
        'strip_prefix': True,
        'headers': {
            'response': {
                'Access-Control-Allow-Origin': '*',
                'Access-Control-Allow-Credentials': "true",
                'Access-Control-Allow-Headers': '*'
            }
        }
    },
)
agent.assert_exp(response['exit_code'] == 0)

## Set up NethCTI-Server to allow https and websocket connections on same host
response = agent.tasks.run(
    agent_id=agent.resolve_agent_id('traefik@node'),
    action='set-route',
    data={
        'instance': os.environ['MODULE_ID'] + '-server-websocket',
        'url':  'http://127.0.0.1:' + os.environ["NETHCTI_SERVER_WS_PORT"] + '/socket.io',
        'http2https':  os.environ["TRAEFIK_HTTP2HTTPS"] == "true",
        'lets_encrypt': lets_encrypt,
        'host': os.environ["NETHVOICE_HOST"],
        'path': '/socket.io',
        'headers': {
            'response': {
                'Access-Control-Allow-Origin': '*',
                'Access-Control-Allow-Credentials': "true",
                'Access-Control-Allow-Headers': '*'
            }
        }
    },
)
agent.assert_exp(response['exit_code'] == 0)

## Set up Janus on same host
response = agent.tasks.run(
    agent_id=agent.resolve_agent_id('traefik@node'),
    action='set-route',
    data={
        'instance': os.environ['MODULE_ID'] + '-janus',
        'url':  'http://127.0.0.1:' + os.environ["JANUS_TRANSPORT_PORT"],
        'http2https':  os.environ["TRAEFIK_HTTP2HTTPS"] == "true",
        'lets_encrypt': lets_encrypt,
        'host': os.environ["NETHVOICE_HOST"],
        'path': '/janus',
        'headers': {
            'response': {
                'Access-Control-Allow-Origin': '*',
                'Access-Control-Allow-Credentials': "true",
                'Access-Control-Allow-Headers': '*'
            }
        }
    },
)
agent.assert_exp(response['exit_code'] == 0)
