#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys

import agent
import agent.tasks

# Find default traefik instance for current node
proxy_id = agent.resolve_agent_id('nethvoice-proxy@node')
if proxy_id is None:
    sys.exit(2)

# Configure nethvoice-proxy to route SIP traffic for Nethvoice
response = agent.tasks.run(
    agent_id=proxy_id,
    action='add-route',
    data={
        'domain': os.environ["NETHVOICE_HOST"],
        'address': [{"uri":"sip:127.0.0.1:"+os.environ["ASTERISK_SIP_PORT"],"description":os.environ["MODULE_ID"]}],
    },
)

# Check if proxy configuration has been successfull
agent.assert_exp(response['exit_code'] == 0)
