#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import agent
import agent.tasks

services_to_restart = set(os.environ['RESTART_SERVICES'].split())

# Get proxy srv records
proxy_id = agent.resolve_agent_id('nethvoice-proxy@node')
ksrv = agent.list_service_providers(agent.redis_connect(use_replica=True), "sip", "tcp", {"module_id": proxy_id.removeprefix("module/")})

# Configure ICE to enforce the proxy ip address.
# Restart services to apply new configuration if needed
if os.environ["ICEENFORCE"] != ksrv[0]["address"]:
    agent.set_env("ICEENFORCE", ksrv[0]["address"])
    services_to_restart.add("janus.service")

agent.set_env("RESTART_SERVICES", " ".join(services_to_restart))
