#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

"""
This file is created with separation of resposability in mind.
This configures API segment of reports.
"""

import json
import sys
import os

import agent

# Fetch request
request = json.load(sys.stdin)

# Set environment variables
agent.set_env('REPORTS_INTERNATIONAL_PREFIX', request['reports_international_prefix'])

# Setup traefik routes
# api endpoint
response = agent.tasks.run(
    agent_id=agent.resolve_agent_id('traefik@node'),
    action='set-route',
    data={
        'instance': os.environ['MODULE_ID'] + '-reports-api',
        'url': 'http://127.0.0.1:' + os.environ["REPORTS_API_PORT"],
        'http2https':  os.environ["TRAEFIK_HTTP2HTTPS"] == "True",
        'lets_encrypt': os.environ["TRAEFIK_LETS_ENCRYPT"] == "True",
        'host': os.environ["NETHVOICE_HOST"],
        'path': '/pbx-report-api',
        'strip_prefix': True
    },
)
agent.assert_exp(response['exit_code'] == 0)
