#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e    # exit immediately if an error occurs
exec 1>&2 # ensure any output is sent to stderr

#restart services if they are already running

if [ -n "$RESTART_SERVICES" ]; then
systemctl --user try-restart $RESTART_SERVICES
fi

# If the control reaches this step, the service can be enabled and started

systemctl --user enable --now mariadb.service
systemctl --user enable --now freepbx.service
systemctl --user enable --now janus.service
systemctl --user enable nethcti-server.service # cti server will be started later
systemctl --user enable --now nethcti-ui.service
systemctl --user enable --now tancredi.service
systemctl --user enable --now phonebook.service
systemctl --user enable --now phonebook-update.timer
systemctl --user enable --now watcher.path
systemctl --user enable --now redis-flexisip.service
systemctl --user enable --now flexisip.service
# Reports
systemctl --user enable --now reports-api.service
systemctl --user enable --now reports-scheduler.timer
systemctl --user enable --now reports-ui.service
