#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
# sourcing the file directly is broken with quotes
MARIADB_ROOT_PASSWORD=$(grep '^MARIADB_ROOT_PASSWORD=' ./passwords.env) && export $MARIADB_ROOT_PASSWORD
# start nethcti-server if wizard step is completed
WIZARD_STEP=$(/usr/bin/podman exec mariadb mysql -u root -h 127.0.0.1 -P $NETHVOICE_MARIADB_PORT -p$MARIADB_ROOT_PASSWORD asterisk -BNe "select step from rest_wizard" | tr -d -c '[:digit:]')
if [[ $WIZARD_STEP -ge 10 ]]; then
    echo "Starting nethcti-server" >> /dev/stderr
    /usr/bin/systemctl --user start nethcti-server
fi

# restart asterisk when convenient
echo "Restarting asterisk when convenient" >> /dev/stderr
/usr/bin/podman exec -d freepbx asterisk -rx "core restart when convenient"