#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

systemctl --user -T try-reload-or-restart flexisip

systemctl --user -T try-reload-or-restart asterisk

systemctl --user -T try-reload-or-restart janus

systemctl --user -T try-reload-or-restart phonebook

systemctl --user -T try-reload-or-restart nethcti-server
