/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;

/*!40103 SET TIME_ZONE='+00:00' */;
USE `nethcti3`;
CREATE TABLE `cti_phonebook` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `owner_id` varchar(255) NOT NULL DEFAULT '',
  `type` varchar(255) NOT NULL DEFAULT '',
  `homeemail` varchar(255) DEFAULT NULL,
  `workemail` varchar(255) DEFAULT NULL,
  `homephone` varchar(25) DEFAULT NULL,
  `workphone` varchar(25) DEFAULT NULL,
  `cellphone` varchar(25) DEFAULT NULL,
  `fax` varchar(25) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `company` varchar(255) DEFAULT NULL,
  `notes` text,
  `name` varchar(255) DEFAULT NULL,
  `homestreet` varchar(255) DEFAULT NULL,
  `homepob` varchar(10) DEFAULT NULL,
  `homecity` varchar(255) DEFAULT NULL,
  `homeprovince` varchar(255) DEFAULT NULL,
  `homepostalcode` varchar(255) DEFAULT NULL,
  `homecountry` varchar(255) DEFAULT NULL,
  `workstreet` varchar(255) DEFAULT NULL,
  `workpob` varchar(10) DEFAULT NULL,
  `workcity` varchar(255) DEFAULT NULL,
  `workprovince` varchar(255) DEFAULT NULL,
  `workpostalcode` varchar(255) DEFAULT NULL,
  `workcountry` varchar(255) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `extension` varchar(255) DEFAULT NULL,
  `speeddial_num` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `owner_idx` (`owner_id`),
  KEY `wemail_idx` (`workemail`),
  KEY `hemail_idx` (`homeemail`),
  KEY `name_idx` (`name`),
  KEY `hphone_idx` (`homephone`),
  KEY `wphone_idx` (`workphone`),
  KEY `cphone_idx` (`cellphone`),
  KEY `extension_idx` (`extension`),
  KEY `fax_idx` (`fax`),
  KEY `company_idx` (`company`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
