/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
USE `asterisk`;
INSERT INTO `rest_pjsip_trunks_custom_flags` (`provider_id`,`keyword`,`value`) VALUES
(1,"disable_topos_header",0),
(2,"disable_topos_header",0),
(3,"disable_topos_header",0),
(4,"disable_topos_header",0),
(5,"disable_topos_header",0),
(6,"disable_topos_header",0),
(7,"disable_topos_header",0),
(8,"disable_topos_header",0),
(9,"disable_topos_header",0),
(10,"disable_topos_header",0),
(11,"disable_topos_header",0),
(12,"disable_topos_header",0),
(13,"disable_topos_header",0),
(14,"disable_topos_header",0),
(15,"disable_topos_header",0),
(16,"disable_topos_header",0),
(17,"disable_topos_header",0),
(18,"disable_topos_header",0),
(19,"disable_topos_header",0),
(20,"disable_topos_header",0),
(21,"disable_topos_header",0),
(22,"disable_topos_header",0),
(23,"disable_topos_header",0),
(24,"disable_topos_header",0),
(1,"disable_srtp_header",1),
(2,"disable_srtp_header",1),
(3,"disable_srtp_header",0),
(4,"disable_srtp_header",1),
(5,"disable_srtp_header",1),
(6,"disable_srtp_header",1),
(7,"disable_srtp_header",1),
(8,"disable_srtp_header",1),
(9,"disable_srtp_header",1),
(10,"disable_srtp_header",0),
(11,"disable_srtp_header",1),
(12,"disable_srtp_header",1),
(13,"disable_srtp_header",1),
(14,"disable_srtp_header",1),
(15,"disable_srtp_header",1),
(16,"disable_srtp_header",1),
(17,"disable_srtp_header",1),
(18,"disable_srtp_header",1),
(19,"disable_srtp_header",1),
(20,"disable_srtp_header",1),
(21,"disable_srtp_header",1),
(22,"disable_srtp_header",1),
(23,"disable_srtp_header",1),
(24,"disable_srtp_header",1);
