/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
USE `asterisk`;
INSERT INTO `soundlang_packages` (`id`,`type`,`module`,`language`,`license`,`author`,`authorlink`,`format`,`version`,`installed`) VALUES
(1,"asterisk","core-sounds","cs","","Westany Ltd.","https://www.westany.com/","alaw","1.5",NULL),
(2,"asterisk","core-sounds","cs","","Westany Ltd.","https://www.westany.com/","g722","1.5",NULL),
(3,"asterisk","core-sounds","cs","","Westany Ltd.","https://www.westany.com/","g729","1.5",NULL),
(4,"asterisk","core-sounds","cs","","Westany Ltd.","https://www.westany.com/","ulaw","1.5",NULL),
(5,"asterisk","core-sounds","en","","Allison Smith","http://www.theivrvoice.com","alaw","1.5",NULL),
(6,"asterisk","core-sounds","en","","Allison Smith","http://www.theivrvoice.com","g722","1.5",NULL),
(7,"asterisk","core-sounds","en","","Allison Smith","http://www.theivrvoice.com","g729","1.5",NULL),
(8,"asterisk","core-sounds","en","","Allison Smith","http://www.theivrvoice.com","ulaw","1.5",NULL),
(9,"asterisk","core-sounds","en","","www.nethesis.it","www.nethesis.it","sln","1.9","1.9"),
(10,"asterisk","core-sounds","en_AU","","CAMSOWN","http://voiceover.camsown.com","alaw","1.5",NULL),
(11,"asterisk","core-sounds","en_AU","","CAMSOWN","http://voiceover.camsown.com","g722","1.5",NULL),
(12,"asterisk","core-sounds","en_AU","","CAMSOWN","http://voiceover.camsown.com","g729","1.5",NULL),
(13,"asterisk","core-sounds","en_AU","","CAMSOWN","http://voiceover.camsown.com","ulaw","1.5",NULL),
(14,"asterisk","core-sounds","en_GB","","Jay Benham","http://www.soundanswers.com/asterisk/","g729","1.5",NULL),
(15,"asterisk","core-sounds","en_NZ","","Rover Voice Services","http://www.rovervoice.co.nz","alaw","1.5",NULL),
(16,"asterisk","core-sounds","en_NZ","","Rover Voice Services","http://www.rovervoice.co.nz","g722","1.5",NULL),
(17,"asterisk","core-sounds","en_NZ","","Rover Voice Services","http://www.rovervoice.co.nz","ulaw","1.5",NULL),
(18,"asterisk","core-sounds","es","","Allison Smith","http://www.theivrvoice.com","alaw","1.5",NULL),
(19,"asterisk","core-sounds","es","","Allison Smith","http://www.theivrvoice.com","g722","1.5",NULL),
(20,"asterisk","core-sounds","es","","Allison Smith","http://www.theivrvoice.com","g729","1.5",NULL),
(21,"asterisk","core-sounds","es","","Allison Smith","http://www.theivrvoice.com","ulaw","1.5",NULL),
(22,"asterisk","core-sounds","fa","","SENA","http://www.senatelecom.ir/","alaw","1.5",NULL),
(23,"asterisk","core-sounds","fa","","SENA","http://www.senatelecom.ir/","g722","1.5",NULL),
(24,"asterisk","core-sounds","fa","","SENA","http://www.senatelecom.ir/","ulaw","1.5",NULL),
(25,"asterisk","core-sounds","fr","","June Wallack","http://www.junewallack.com","alaw","1.5",NULL),
(26,"asterisk","core-sounds","fr","","June Wallack","http://www.junewallack.com","g722","1.5",NULL),
(27,"asterisk","core-sounds","fr","","June Wallack","http://www.junewallack.com","g729","1.5",NULL),
(28,"asterisk","core-sounds","fr","","June Wallack","http://www.junewallack.com","ulaw","1.5",NULL),
(29,"asterisk","core-sounds","he","","Westany Ltd.","https://www.westany.com/","alaw","1.5",NULL),
(30,"asterisk","core-sounds","he","","Westany Ltd.","https://www.westany.com/","g722","1.5",NULL),
(31,"asterisk","core-sounds","he","","Westany Ltd.","https://www.westany.com/","g729","1.5",NULL),
(32,"asterisk","core-sounds","he","","Westany Ltd.","https://www.westany.com/","ulaw","1.5",NULL),
(33,"asterisk","core-sounds","it","","Carlo Flora","http://www.segreterietelefoniche.it","alaw","1.5",NULL),
(34,"asterisk","core-sounds","it","","Carlo Flora","http://www.segreterietelefoniche.it","g722","1.5",NULL),
(35,"asterisk","core-sounds","it","","Carlo Flora","http://www.segreterietelefoniche.it","g729","1.5",NULL),
(36,"asterisk","core-sounds","it","","Carlo Flora","http://www.segreterietelefoniche.it","ulaw","1.5",NULL),
(37,"asterisk","core-sounds","it","","www.nethesis.it","www.nethesis.it","sln","1.9","1.9"),
(38,"asterisk","core-sounds","ja","","Ryoko SONODA (QLOOG, Inc.)","http://www.qloog.com","alaw","1.5",NULL),
(39,"asterisk","core-sounds","ja","","Ryoko SONODA (QLOOG, Inc.)","http://www.qloog.com","g722","1.5",NULL),
(40,"asterisk","core-sounds","ja","","Ryoko SONODA (QLOOG, Inc.)","http://www.qloog.com","g729","1.5",NULL),
(41,"asterisk","core-sounds","ja","","Ryoko SONODA (QLOOG, Inc.)","http://www.qloog.com","ulaw","1.5",NULL),
(42,"asterisk","core-sounds","nl","","Westany Ltd.","https://www.westany.com/","alaw","1.5",NULL),
(43,"asterisk","core-sounds","nl","","Westany Ltd.","https://www.westany.com/","g722","1.5",NULL),
(44,"asterisk","core-sounds","nl","","Westany Ltd.","https://www.westany.com/","g729","1.5",NULL),
(45,"asterisk","core-sounds","nl","","Westany Ltd.","https://www.westany.com/","ulaw","1.5",NULL),
(46,"asterisk","core-sounds","no","","Westany Ltd.","https://www.westany.com/","alaw","1.5",NULL),
(47,"asterisk","core-sounds","no","","Westany Ltd.","https://www.westany.com/","g722","1.5",NULL),
(48,"asterisk","core-sounds","no","","Westany Ltd.","https://www.westany.com/","g729","1.5",NULL),
(49,"asterisk","core-sounds","no","","Westany Ltd.","https://www.westany.com/","ulaw","1.5",NULL),
(50,"asterisk","core-sounds","pl","","Westany Ltd.","https://www.westany.com/","alaw","1.5",NULL),
(51,"asterisk","core-sounds","pl","","Westany Ltd.","https://www.westany.com/","g722","1.5",NULL),
(52,"asterisk","core-sounds","pl","","Westany Ltd.","https://www.westany.com/","g729","1.5",NULL),
(53,"asterisk","core-sounds","pl","","Westany Ltd.","https://www.westany.com/","ulaw","1.5",NULL),
(54,"asterisk","core-sounds","ru","","http://www.ivrvoice.ru/","www.ivrvoice.ru","alaw","1.5",NULL),
(55,"asterisk","core-sounds","ru","","http://www.ivrvoice.ru/","www.ivrvoice.ru","g722","1.5",NULL),
(56,"asterisk","core-sounds","ru","","http://www.ivrvoice.ru/","www.ivrvoice.ru","g729","1.5",NULL),
(57,"asterisk","core-sounds","ru","","http://www.ivrvoice.ru/","www.ivrvoice.ru","ulaw","1.5",NULL),
(58,"asterisk","core-sounds","sv","","Tove Hjelm","http://www.thenordicvoice.com","alaw","1.5",NULL),
(59,"asterisk","core-sounds","sv","","Tove Hjelm","http://www.thenordicvoice.com","g722","1.5",NULL),
(60,"asterisk","core-sounds","sv","","Tove Hjelm","http://www.thenordicvoice.com","g729","1.5",NULL),
(61,"asterisk","core-sounds","sv","","Tove Hjelm","http://www.thenordicvoice.com","ulaw","1.5",NULL),
(62,"asterisk","core-sounds","tr","","Westany Ltd.","https://www.westany.com/","alaw","1.5",NULL),
(63,"asterisk","core-sounds","tr","","Westany Ltd.","https://www.westany.com/","g722","1.5",NULL),
(64,"asterisk","core-sounds","tr","","Westany Ltd.","https://www.westany.com/","g729","1.5",NULL),
(65,"asterisk","core-sounds","tr","","Westany Ltd.","https://www.westany.com/","ulaw","1.5",NULL),
(66,"asterisk","extra-sounds","en","","Allison Smith","http://www.theivrvoice.com","alaw","1.5",NULL),
(67,"asterisk","extra-sounds","en","","Allison Smith","http://www.theivrvoice.com","g722","1.5",NULL),
(68,"asterisk","extra-sounds","en","","Allison Smith","http://www.theivrvoice.com","g729","1.5",NULL),
(69,"asterisk","extra-sounds","en","","Allison Smith","http://www.theivrvoice.com","ulaw","1.5",NULL),
(70,"asterisk","extra-sounds","en","","www.nethesis.it","www.nethesis.it","sln","1.9","1.9"),
(71,"asterisk","extra-sounds","en_GB","","Jay Benham","http://www.soundanswers.com/asterisk/","g729","1.5",NULL),
(72,"asterisk","extra-sounds","fr","","June Wallack","http://www.junewallack.com","alaw","1.5",NULL),
(73,"asterisk","extra-sounds","fr","","June Wallack","http://www.junewallack.com","g722","1.5",NULL),
(74,"asterisk","extra-sounds","fr","","June Wallack","http://www.junewallack.com","g729","1.5",NULL),
(75,"asterisk","extra-sounds","fr","","June Wallack","http://www.junewallack.com","ulaw","1.5",NULL),
(76,"freepbx","module-sounds","cs","","Westany Ltd.","https://www.westany.com/","alaw","1.5.0",NULL),
(77,"freepbx","module-sounds","cs","","Westany Ltd.","https://www.westany.com/","g722","1.5.0",NULL),
(78,"freepbx","module-sounds","cs","","Westany Ltd.","https://www.westany.com/","g729","1.5.0",NULL),
(79,"freepbx","module-sounds","cs","","Westany Ltd.","https://www.westany.com/","ulaw","1.5.0",NULL),
(80,"freepbx","module-sounds","en_AU","","CAMSOWN","http://voiceover.camsown.com","alaw","1.5.0",NULL),
(81,"freepbx","module-sounds","en_AU","","CAMSOWN","http://voiceover.camsown.com","g722","1.5.0",NULL),
(82,"freepbx","module-sounds","en_AU","","CAMSOWN","http://voiceover.camsown.com","ulaw","1.5.0",NULL),
(83,"freepbx","module-sounds","en_NZ","","Rover Voice Services","http://www.rovervoice.co.nz","alaw","1.5.0",NULL),
(84,"freepbx","module-sounds","en_NZ","","Rover Voice Services","http://www.rovervoice.co.nz","g722","1.5.0",NULL),
(85,"freepbx","module-sounds","en_NZ","","Rover Voice Services","http://www.rovervoice.co.nz","ulaw","1.5.0",NULL),
(86,"freepbx","module-sounds","es","","Allison Smith","http://www.theivrvoice.com","alaw","1.5.0",NULL),
(87,"freepbx","module-sounds","es","","Allison Smith","http://www.theivrvoice.com","g722","1.5.0",NULL),
(88,"freepbx","module-sounds","es","","Allison Smith","http://www.theivrvoice.com","ulaw","1.5.0",NULL),
(89,"freepbx","module-sounds","fa","","SENA","http://www.senatelecom.ir/","alaw","1.5.0",NULL),
(90,"freepbx","module-sounds","fa","","SENA","http://www.senatelecom.ir/","g722","1.5.0",NULL),
(91,"freepbx","module-sounds","fa","","SENA","http://www.senatelecom.ir/","ulaw","1.5.0",NULL),
(92,"freepbx","module-sounds","fr","","June Wallack","http://www.junewallack.com","alaw","1.5.0",NULL),
(93,"freepbx","module-sounds","fr","","June Wallack","http://www.junewallack.com","g722","1.5.0",NULL),
(94,"freepbx","module-sounds","fr","","June Wallack","http://www.junewallack.com","ulaw","1.5.0",NULL),
(95,"freepbx","module-sounds","he","","Westany Ltd.","https://www.westany.com/","alaw","1.5.0",NULL),
(96,"freepbx","module-sounds","he","","Westany Ltd.","https://www.westany.com/","g722","1.5.0",NULL),
(97,"freepbx","module-sounds","he","","Westany Ltd.","https://www.westany.com/","g729","1.5.0",NULL),
(98,"freepbx","module-sounds","he","","Westany Ltd.","https://www.westany.com/","ulaw","1.5.0",NULL),
(99,"freepbx","module-sounds","it","","Carlo Flora","http://www.segreterietelefoniche.it","alaw","1.5.0",NULL),
(100,"freepbx","module-sounds","it","","Carlo Flora","http://www.segreterietelefoniche.it","g722","1.5.0",NULL),
(101,"freepbx","module-sounds","it","","Carlo Flora","http://www.segreterietelefoniche.it","ulaw","1.5.0",NULL),
(102,"asterisk","extra-sounds","it","","www.nethesis.it","www.nethesis.it","sln","1.9","1.9"),
(103,"freepbx","module-sounds","ja","","Ryoko SONODA (QLOOG, Inc.)","http://www.qloog.com","alaw","1.5.1",NULL),
(104,"freepbx","module-sounds","ja","","Ryoko SONODA (QLOOG, Inc.)","http://www.qloog.com","g722","1.5.1",NULL),
(105,"freepbx","module-sounds","ja","","Ryoko SONODA (QLOOG, Inc.)","http://www.qloog.com","ulaw","1.5.1",NULL),
(106,"freepbx","module-sounds","nl","","Westany Ltd.","https://www.westany.com/","alaw","1.5.0",NULL),
(107,"freepbx","module-sounds","nl","","Westany Ltd.","https://www.westany.com/","g722","1.5.0",NULL),
(108,"freepbx","module-sounds","nl","","Westany Ltd.","https://www.westany.com/","g729","1.5.0",NULL),
(109,"freepbx","module-sounds","nl","","Westany Ltd.","https://www.westany.com/","ulaw","1.5.0",NULL),
(110,"freepbx","module-sounds","no","","Westany Ltd.","https://www.westany.com/","alaw","1.5.0",NULL),
(111,"freepbx","module-sounds","no","","Westany Ltd.","https://www.westany.com/","g722","1.5.0",NULL),
(112,"freepbx","module-sounds","no","","Westany Ltd.","https://www.westany.com/","g729","1.5.0",NULL),
(113,"freepbx","module-sounds","no","","Westany Ltd.","https://www.westany.com/","ulaw","1.5.0",NULL),
(114,"freepbx","module-sounds","pl","","Westany Ltd.","https://www.westany.com/","alaw","1.5.0",NULL),
(115,"freepbx","module-sounds","pl","","Westany Ltd.","https://www.westany.com/","g722","1.5.0",NULL),
(116,"freepbx","module-sounds","pl","","Westany Ltd.","https://www.westany.com/","g729","1.5.0",NULL),
(117,"freepbx","module-sounds","pl","","Westany Ltd.","https://www.westany.com/","ulaw","1.5.0",NULL),
(118,"freepbx","module-sounds","ru","","http://www.ivrvoice.ru/","www.ivrvoice.ru","alaw","1.5.0",NULL),
(119,"freepbx","module-sounds","ru","","http://www.ivrvoice.ru/","www.ivrvoice.ru","g722","1.5.0",NULL),
(120,"freepbx","module-sounds","ru","","http://www.ivrvoice.ru/","www.ivrvoice.ru","ulaw","1.5.0",NULL),
(121,"freepbx","module-sounds","tr","","Westany Ltd.","https://www.westany.com/","alaw","1.5.0",NULL),
(122,"freepbx","module-sounds","tr","","Westany Ltd.","https://www.westany.com/","g722","1.5.0",NULL),
(123,"freepbx","module-sounds","tr","","Westany Ltd.","https://www.westany.com/","g729","1.5.0",NULL),
(124,"freepbx","module-sounds","tr","","Westany Ltd.","https://www.westany.com/","ulaw","1.5.0",NULL),
(125,"asterisk","core-sounds","de_DE","","Zapp Media (Berlin)","zappmedia.qtn.net","alaw","1.5",NULL),
(126,"asterisk","core-sounds","de_DE","","Zapp Media (Berlin)","zappmedia.qtn.net","g722","1.5",NULL),
(127,"asterisk","core-sounds","de_DE","","Zapp Media (Berlin)","zappmedia.qtn.net","ulaw","1.5",NULL),
(128,"asterisk","core-sounds","en_GB","","Jay Benham","http://www.soundanswers.com/asterisk/","alaw","1.5.1",NULL),
(129,"asterisk","core-sounds","en_GB","","Jay Benham","http://www.soundanswers.com/asterisk/","g722","1.5.1",NULL),
(130,"asterisk","core-sounds","en_GB","","Jay Benham","http://www.soundanswers.com/asterisk/","ulaw","1.5.1",NULL),
(131,"asterisk","extra-sounds","en_GB","","Jay Benham","http://www.soundanswers.com/asterisk/","alaw","1.5.1",NULL),
(132,"asterisk","extra-sounds","en_GB","","Jay Benham","http://www.soundanswers.com/asterisk/","g722","1.5.1",NULL),
(133,"asterisk","extra-sounds","en_GB","","Jay Benham","http://www.soundanswers.com/asterisk/","ulaw","1.5.1",NULL),
(134,"freepbx","module-sounds","en_GB","","Jay Benham","http://www.soundanswers.com/asterisk/","alaw","1.5.1",NULL),
(135,"freepbx","module-sounds","en_GB","","Jay Benham","http://www.soundanswers.com/asterisk/","g722","1.5.1",NULL),
(136,"freepbx","module-sounds","en_GB","","Jay Benham","http://www.soundanswers.com/asterisk/","ulaw","1.5.1",NULL);
