/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
USE `asterisk`;
INSERT INTO `notifications` (`module`,`id`,`level`,`display_text`,`extended_text`,`link`,`reset`,`candelete`,`timestamp`) VALUES
("framework","BROWSER_STATS",600,"Collecting Anonymous Browser Stats","The FreePBX project is collecting anonymous browser statistics using google analytics. These are used to focus development efforts based on real user input. All information is anonymous. You can disable this in Advanced Settings with the Browser Stats setting.","",0,1,1617118566),
("framework","missing_html5",600,"Missing HTML5 format converters","You are missing support for the following HTML5 codecs: m4a,mp3. To fully support HTML5 browser playback you will need to install programs that can not be distributed with FreePBX. If you\'d like to install the binaries needed for these conversions click \'Resolve\' in the lower left corner of this message. You can also safely ignore this message but browser playback might not work in your browser.","http://wiki.freepbx.org/display/FOP/Installing+Media+Conversion+Libraries",0,1,1617118566),
("freepbx","SIGNATURE_CHECK",600,"Signature checking is disabled","FreePBX Module Signature checking has been disabled. Your system could be exposed to security vulnerabilities from compromised or tampered code","",0,1,1665038063),
("freepbx","VULNERABILITIES_FIXED",600,"Modules vulnerable to security threats have been automatically updated","logfiles has been automatically upgraded to fix security issues: SEC-2020-005\ncel has been automatically upgraded to fix security issues: SEC-2020-006, SEC-2020-001\ncdr has been automatically upgraded to fix security issues: SEC-2020-007\nframework has been automatically upgraded to fix security issues: SEC-2019-000\nuserman has been automatically upgraded to fix security issues: SEC-2019-003\nlogfiles has been automatically upgraded to fix security issues: SEC-2020-005\ncel has been automatically upgraded to fix security issues: SEC-2020-006, SEC-2020-001\ncdr has been automatically upgraded to fix security issues: SEC-2020-007\nframework has been automatically upgraded to fix security issues: SEC-2019-000\nuserman has been automatically upgraded to fix security issues: SEC-2019-003\nlogfiles has been automatically upgraded to fix security issues: SEC-2020-005\ncel has been automatically upgraded to fix security issues: SEC-2020-006, SEC-2020-001\ncdr has been automatically upgraded to fix security issues: SEC-2020-007\nframework has been automatically upgraded to fix security issues: SEC-2019-000\nuserman has been automatically upgraded to fix security issues: SEC-2019-003\nlogfiles has been automatically upgraded to fix security issues: SEC-2020-005\ncel has been automatically upgraded to fix security issues: SEC-2020-006, SEC-2020-001\ncdr has been automatically upgraded to fix security issues: SEC-2020-007\nframework has been automatically upgraded to fix security issues: SEC-2019-000\nuserman has been automatically upgraded to fix security issues: SEC-2019-003\nlogfiles has been automatically upgraded to fix security issues: SEC-2020-005\ncel has been automatically upgraded to fix security issues: SEC-2020-006, SEC-2020-001\ncdr has been automatically upgraded to fix security issues: SEC-2020-007\nframework has been automatically upgraded to fix security issues: SEC-2019-000\nuserman has been automatically upgraded to fix security issues: SEC-2019-003\n","",0,1,1665202153),
("sipsettings","BINDPORT",600,"Default bind port for CHAN_PJSIP is: 5060, CHAN_SIP is: 5160","The default bind ports for FreePBX have changed. Please keep this is mind while configuring your devices. You can change this in SIP Settings. CHAN_PJSIP is: 5060, CHAN_SIP is: 5160","http://wiki.freepbx.org/display/HTGS/CHAN_PJSIP+vs+CHAN_SIP",0,1,1617118488);
