/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
USE `asterisk`;
INSERT INTO `customcontexts_includes_list` (`context`,`include`,`description`,`missing`,`sort`) VALUES
("from-internal","from-internal-additional","ENTIRE Basic Internal Dialplan",0,0),
("from-internal","from-internal-custom","Custom Internal Dialplan",0,0),
("from-internal","parkedcalls","Call Parking",0,0),
("from-internal-additional","app-blacklist","app-blacklist",0,39),
("from-internal-additional","app-calltrace","app-calltrace",0,24),
("from-internal-additional","app-callwaiting-cwoff","app-callwaiting-cwoff",0,14),
("from-internal-additional","app-callwaiting-cwon","app-callwaiting-cwon",0,15),
("from-internal-additional","app-cf-busy-off","app-cf-busy-off",0,5),
("from-internal-additional","app-cf-busy-off-any","app-cf-busy-off-any",0,4),
("from-internal-additional","app-cf-busy-on","app-cf-busy-on",0,3),
("from-internal-additional","app-cf-busy-prompting-on","app-cf-busy-prompting-on",0,2),
("from-internal-additional","app-cf-off","app-cf-off",0,6),
("from-internal-additional","app-cf-off-any","app-cf-off-any",0,7),
("from-internal-additional","app-cf-on","app-cf-on",0,11),
("from-internal-additional","app-cf-prompting-on","app-cf-prompting-on",0,12),
("from-internal-additional","app-cf-toggle","app-cf-toggle",0,1),
("from-internal-additional","app-cf-unavailable-off","app-cf-unavailable-off",0,10),
("from-internal-additional","app-cf-unavailable-on","app-cf-unavailable-on",0,9),
("from-internal-additional","app-cf-unavailable-prompt-on","app-cf-unavailable-prompt-on",0,8),
("from-internal-additional","app-chanspy","app-chanspy",0,44),
("from-internal-additional","app-dialvm","app-dialvm",0,37),
("from-internal-additional","app-dnd-off","app-dnd-off",0,17),
("from-internal-additional","app-dnd-on","app-dnd-on",0,18),
("from-internal-additional","app-dnd-toggle","app-dnd-toggle",0,19),
("from-internal-additional","app-echo-test","app-echo-test",0,25),
("from-internal-additional","app-fmf-toggle","app-fmf-toggle",0,21),
("from-internal-additional","app-parking","app-parking",0,30),
("from-internal-additional","app-pickup","app-pickup",0,43),
("from-internal-additional","app-rapidcode","app-rapidcode",0,32),
("from-internal-additional","app-recordings","app-recordings",0,33),
("from-internal-additional","app-speakextennum","app-speakextennum",0,26),
("from-internal-additional","app-speakingclock","app-speakingclock",0,27),
("from-internal-additional","app-vmmain","app-vmmain",0,38),
("from-internal-additional","cti-conference","cti-conference",0,40),
("from-internal-additional","ext-cf-hints","ext-cf-hints",0,13),
("from-internal-additional","ext-dnd-hints","ext-dnd-hints",0,20),
("from-internal-additional","ext-findmefollow","ext-findmefollow",0,22),
("from-internal-additional","ext-group","ext-group",0,34),
("from-internal-additional","ext-intercom-users","ext-intercom-users",0,28),
("from-internal-additional","ext-local","ext-local",0,46),
("from-internal-additional","ext-local-confirm","ext-local-confirm",0,41),
("from-internal-additional","ext-meetme","ext-meetme",0,16),
("from-internal-additional","ext-queues","ext-queues",0,31),
("from-internal-additional","ext-test","ext-test",0,45),
("from-internal-additional","findmefollow-ringallv2","findmefollow-ringallv2",0,42),
("from-internal-additional","fmgrps","fmgrps",0,23),
("from-internal-additional","grps","grps",0,35),
("from-internal-additional","outbound-allroutes","ALL OUTBOUND ROUTES",0,47),
("from-internal-additional","park-hints","park-hints",0,29),
("from-internal-additional","vmblast-grp","vmblast-grp",0,36);
