/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
USE `asterisk`;
INSERT INTO `providers` (`provider`,`description`,`dettpeer`,`dettuser`,`registration`) VALUES
("activenetwork","Active Network","disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nhost=sip.activenetwork.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=sip.activenetwork.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME\nfromdomain=sip.activenetwork.it","allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833","USERNAME:PASSWORD@sip.activenetwork.it/NUMERO"),
("cheapnet","Cheapnet","disallow=all\nallow=CODECS\ndtmfmode=rfc2833\nfromdomain=sip.cheapnet.it\nhost=sip.cheapnet.it\nqualify=yes\nsecret=PASSWORD\ntype=friend\nnat=yes\nusername=USERNAME\ncanreinvite=no\ncontext=from-pstn\nsendrpid=no\ninsecure=port,invite","allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833","USERNAME:PASSWORD@sip.cheapnet.it/NUMERO"),
("clouditalia","Clouditalia","disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nhost=voip.eutelia.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=voip.eutelia.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME","allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833","USERNAME:PASSWORD@voip.eutelia.it/NUMERO"),
("messagenet","MessageNet","disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nhost=sip.messagenet.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=sip.messagenet.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nusername=USERNAME","allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833","USERNAME:PASSWORD@sip.messagenet.it/NUMERO"),
("neomedia","Neomedia","disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nhost=sip.neomedia.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=sip.neomedia.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME\nfromdomain=sip.neomedia.it","allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833","USERNAME:PASSWORD@sip.neomedia.it/NUMERO"),
("opensolution_sip","Opensolution Sip","disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nfromdomain=sip.opensolution.it\nhost=sip.opensolution.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=sip.opensolution.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME","allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833","USERNAME:PASSWORD@sip.opensolution.it/NUMERO"),
("opensolution_voip","Opensolution Voip","disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nfromdomain=voip.opensolution.it\nhost=voip.opensolution.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=voip.opensolution.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME","allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833","USERNAME:PASSWORD@voip.opensolution.it/NUMERO"),
("sixcomm","Six Comm Group - Fibering S.p.A.","username=USERNAME\ntype=friend\nsecret=PASSWORD\nqualify=yes\ninsecure=port,invite\nhost=voip.sixcomm.net\ndtmfmode=rfc2833\nallow=CODECS","type=USERNAME\nsecret=PASSWORD\ninsecure=port,invite\ncontext=from-trunk\ndtmfmode=rfc2833\nallow=CODECS","USERNAME@voip.sixcomm.net:PASSWORD:USERNAME@pcscf.sixcomm.net/USERNAME"),
("talkho","Talkho","disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nhost=sip.talkho.com\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=sip.talkho.com\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME\nfromdomain=sip.talkho.com","allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833","USERNAME:PASSWORD@sip.talkho.com/NUMERO"),
("timenet","Timenet","disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nhost=sbc.voipvox.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=sbc.voipvox.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME\nfromdomain=sbc.voipvox.it","allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833","USERNAME:PASSWORD@sbc.voipvox.it/NUMERO"),
("twt","TWT","disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=NUMERO\nhost=res.sip.twt.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=res.sip.twt.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME\nfromdomain=res.sip.twt.it","allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833","USERNAME:PASSWORD@res.sip.twt.it/NUMERO"),
("vivavox","VivaVox","disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nhost=voip.vivavox.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=voip.vivavox.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME\nfromdomain=voip.vivavox.it","allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833","USERNAME:PASSWORD@voip.vivavox.it/NUMERO"),
("voipeasy","VoipEasy","disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nhost=sip.voipeasy.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=sip.voipeasy.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME\ndomain=sip.voipeasy.it\nfromdomain=sip.voipeasy.it","allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833","USERNAME:PASSWORD@sip.voipeasy.it/NUMERO"),
("voiptel","VoipTel","disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nhost=voip.voiptelitalia.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=voip.voiptelitalia.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME\nfromdomain=voip.voiptelitalia.it","allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833","USERNAME:PASSWORD@voip.voiptelitalia.it/NUMERO"),
("voipvoice-sip","VoipVoice (sip.voipvoice.it)","disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nhost=sip.voipvoicetel.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=sip.voipvoicetel.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME\nfromdomain=sip.voipvoicetel.it","allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833","USERNAME:PASSWORD@sip.voipvoicetel.it/NUMERO"),
("voipvoice-trunk","VoipVoice (trunk.voipvoice.it)","disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nhost=trunk.voipvoice.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=trunk.voipvoice.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME\nfromdomain=trunk.voipvoice.it","allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833","USERNAME:PASSWORD@trunk.voipvoice.it/NUMERO"),
("voipvoice-user","VoipVoice (user.voipvoice.it)","disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nhost=user.voipvoice.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=user.voipvoice.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME\nfromdomain=user.voipvoice.it","allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833","USERNAME:PASSWORD@user.voipvoice.it/NUMERO"),
("wicity","WiCity","disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nhost=sip.wicity.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=sip.wicity.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME\nfromdomain=sip.wicity.it","allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833","USERNAME:PASSWORD@sip.wicity.it/NUMERO"),
("xera","Xera","disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=NUMERO\nhost=res.sip.twt.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=res.sip.twt.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME\nfromdomain=res.sip.twt.it","allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833","USERNAME:PASSWORD@res.sip.twt.it/NUMERO"),
("xstream","XSTREAM","disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nfromdomain=nomecliente.site\nhost=128.65.200.18\ninsecure=invite\nnat=yes\nport=5083\nqualify=yes\nrealm=nomecliente.site\nsecret=PASSWORD\nsrvlookup=yes\ntype=peer\nusername=USERNAME","allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833","NUMERO@nomecliente.site:PASSWORD@128.65.200.18:5083");
