/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
USE `asterisk`;
INSERT INTO `featurecodes` (`modulename`,`featurename`,`description`,`helptext`,`defaultcode`,`customcode`,`enabled`,`providedest`) VALUES
("blacklist","blacklist_add","Blacklist a number","Adds a number to the Blacklist Module.  All calls from that number to the system will receive a disconnect recording.  Manage these in the Blacklist module.","*30","",1,1),
("blacklist","blacklist_last","Blacklist the last caller","Adds the last caller to the Blacklist Module.  All calls from that number to the system will receive a disconnect recording.","*32","",1,0),
("blacklist","blacklist_remove","Remove a number from the blacklist","Removes a number from the Blacklist Module","*31","",1,1),
("bosssecretary","bsc_off","Bosssecretary Off","","*154","",1,0),
("bosssecretary","bsc_on","Bosssecretary On","","*153","",1,0),
("bosssecretary","bsc_toggle","Bosssecretary Toggle","","*152","",1,0),
("callforward","cf_toggle","Call Forward Toggle","","*96","",1,0),
("callforward","cfboff","Call Forward Busy Deactivate","","*91","",1,0),
("callforward","cfboff_any","Call Forward Busy Prompting Deactivate","","*92","",1,0),
("callforward","cfbon","Call Forward Busy Activate","","*90","",1,0),
("callforward","cfbpon","Call Forward Busy Prompting Activate","","*94","",1,0),
("callforward","cfoff","Call Forward All Deactivate","","*73","",1,0),
("callforward","cfoff_any","Call Forward All Prompting Deactivate","","*74","",1,0),
("callforward","cfon","Call Forward All Activate","","*72","",1,0),
("callforward","cfpon","Call Forward All Prompting Activate","","*93","",1,0),
("callforward","cfuoff","Call Forward No Answer/Unavailable Deactivate","","*53","",1,0),
("callforward","cfuon","Call Forward No Answer/Unavailable Activate","","*52","",1,0),
("callforward","cfupon","Call Forward No Answer/Unavailable Prompting Activate","","*95","",1,0),
("callwaiting","cwoff","Call Waiting - Deactivate","","*71","",1,0),
("callwaiting","cwon","Call Waiting - Activate","","*70","",1,0),
("campon","cancel","Camp-On Cancel","","*83",NULL,1,0),
("campon","request","Camp-On Request","","*82",NULL,1,0),
("campon","toggle","Camp-On Toggle","","*84",NULL,1,0),
("conferences","conf_status","Conference Status","","*87","",1,0),
("core","atxfer","In-Call Asterisk Attended Transfer","","*2","",1,0),
("core","automon","In-Call Asterisk Toggle Call Recording","","*1","",1,0),
("core","blindxfer","In-Call Asterisk Blind Transfer","","##","",1,0),
("core","chanspy","ChanSpy","","555","",1,1),
("core","disconnect","In-Call Asterisk Disconnect Code","","**","*#",1,0),
("core","pickup","Directed Call Pickup","","**","",1,0),
("core","pickupexten","Asterisk General Call Pickup","","*8","",1,0),
("core","simu_pstn","Simulate Incoming Call","","7777","",1,1),
("core","userlogoff","User Logoff","","*12","",0,0),
("core","userlogon","User Logon","","*11","",0,0),
("dictate","dodictate","Perform dictation","","*34",NULL,1,0),
("dictate","senddictate","Email completed dictation","","*35",NULL,1,0),
("donotdisturb","dnd_off","DND Deactivate","","*79","",1,0),
("donotdisturb","dnd_on","DND Activate","","*78","",1,0),
("donotdisturb","dnd_toggle","DND Toggle","","*76","",1,0),
("extraoptions","atxfercallbackretries","Call back retries","In-Call. Number of times to attempt to send the call back to the transferer.","2",NULL,1,0),
("extraoptions","atxferloopdelay","Number of seconds to sleep between retries","In-Call. Number of seconds to sleep between retries (if atxferdropcall = no)","10",NULL,1,0),
("extraoptions","atxfernoanswertimeout","Attended transfer timeout","In-Call. Timeout for answer on attended transfer default is 15 seconds.","15",NULL,1,0),
("extraoptions","featuredigittimeout","Max time between digits for feature activation","In-Call. Max time (ms) between digits for feature activation (default is 1000 ms)","1000",NULL,1,0),
("extraoptions","transferdigittimeout","Seconds to wait between digits when transferring","In-Call. Number of seconds to wait between digits when transferring a call","3",NULL,1,0),
("fax","simu_fax","Dial System FAX","","666","",1,1),
("findmefollow","fmf_toggle","Findme Follow Toggle","","*21","",1,0),
("hotelwakeup","hotelwakeup","Wake Up Calls","","*68",NULL,1,0),
("infoservices","calltrace","Call Trace","","*69","",1,0),
("infoservices","echotest","Echo Test","","*43","",1,1),
("infoservices","speakextennum","Speak Your Exten Number","","*65","",1,0),
("infoservices","speakingclock","Speaking Clock","","*60","",1,1),
("nethcti3","incall_audio","Incall Audio","NethCTI 3 Incall Audio","1987",NULL,1,0),
("nethcti3","meetme_conf","Conference","NethCTI 3 conference","987",NULL,1,0),
("paging","intercom-off","User Intercom Disallow","","*55","",1,0),
("paging","intercom-on","User Intercom Allow","","*54","",1,0),
("paging","intercom-prefix","Intercom prefix","","*80","",1,0),
("parking","parkedcall","Pickup ParkedCall Prefix","Defines the Feature Code to use to force pickup a call that is parked in a private lot that the extension picking up the call does not have permissions for.  Example if a caller is parked in slot 81 and extension 8001 does not have permission to that private lot they could dial *8581 to pickup the parked call.","*85","",1,1),
("parking","parkto","Park to your Assigned Lot","Parks to your Assigned Lot if using Park Pro. If using standard parking this parks to the default lot","*88","",1,1),
("queues","que_callers","Playback Queue Caller Count","","*47","",1,0),
("queues","que_pause_toggle","Queue Pause Toggle","","*46","",1,0),
("queues","que_toggle","Allow Dynamic Members of a Queue to login or logout. See the Queues Module for how to assign a Dynamic Member to a Queue.","","*45","",1,0),
("rapidcode","rapidcode","Call Rapidcode","","*99","",1,0),
("speeddial","callspeeddial","Speeddial prefix","","*0",NULL,1,0),
("speeddial","setspeeddial","Set user speed dial","","*75",NULL,1,0),
("voicemail","dialvoicemail","Dial Voicemail","The Feature Code used to dial any voicemail","*98","",1,1),
("voicemail","directdialvoicemail","Direct Dial Prefix","","*","",1,0),
("voicemail","myvoicemail","My Voicemail","The Feature Code used to direct dial a users voicemail from their own extension","*97","",1,0);
