FROM docker.io/library/alpine:latest as base
WORKDIR /usr/share/phonebook/

RUN apk add --no-cache \
        nodejs \
        npm \
	curl

RUN mkdir -p /usr/share/phonebookjs
COPY package.json package-lock.json phonebook.js /usr/share/phonebookjs/
RUN cd /usr/share/phonebookjs && \
	npm install && \
	mkdir -p /etc/certificates

COPY usr/local/bin/import-certificate /usr/local/bin/import-certificate
COPY entrypoint.sh /entrypoint
ENTRYPOINT ["/entrypoint"]
CMD [ "/usr/bin/node","/usr/share/phonebookjs/phonebook.js","/etc/config_ldaps.json"]
