FROM docker.io/library/alpine:latest as base
WORKDIR /usr/share/phonebook/

RUN apk add --no-cache \
        nodejs \
        npm \
	curl

RUN	\
	mkdir -p /usr/share/phonebookjs && \
	curl -L https://github.com/nethesis/nethserver-phonebook-mysql/archive/refs/heads/ns8.tar.gz -o - | tar xzp --strip-component=5 -C /usr/share/phonebookjs nethserver-phonebook-mysql-ns8/root/usr/share/phonebookjs && \
	cd /usr/share/phonebookjs && \
	npm install && \
	mkdir -p /etc/certificates

COPY usr/local/bin/import-certificate /usr/local/bin/import-certificate
COPY entrypoint.sh /entrypoint
ENTRYPOINT ["/entrypoint"]
CMD [ "/usr/bin/node","/usr/share/phonebookjs/phonebook.js","/etc/config_ldaps.json"]
