FROM docker.io/library/node:14.21.2-alpine as base
WORKDIR /app

# Clone repo, using base as sidecar
FROM base as repofetcher
ARG NETHVOICE_REPORT_VERSION=refresh-package-lock
RUN apk add --no-cache git \
    && git clone --depth 1 --branch ${NETHVOICE_REPORT_VERSION} https://github.com/nethesis/nethvoice-report

FROM base as build
COPY --from=repofetcher /app/nethvoice-report/ui/package.json .
COPY --from=repofetcher /app/nethvoice-report/ui/package-lock.json .
RUN npm ci
COPY --from=repofetcher /app/nethvoice-report/ui/public public
COPY --from=repofetcher /app/nethvoice-report/ui/src src
COPY --from=repofetcher /app/nethvoice-report/ui/.browserslistrc .
COPY --from=repofetcher /app/nethvoice-report/ui/.eslintrc.js .
COPY --from=repofetcher /app/nethvoice-report/ui/babel.config.js .
COPY --from=repofetcher /app/nethvoice-report/ui/vue.config.js .
ENV NODE_ENV=production
RUN rm public/config/config.production.js \
    && npm run build

FROM docker.io/library/nginx:1.23.3-alpine
COPY --from=build /app/dist /usr/share/nginx/html
