FROM docker.io/library/debian:10.13-slim

RUN apt-get update \
    && apt-get install -y \
        gnupg2 \
        wget \
    && echo 'deb [arch=amd64] http://linphone.org/snapshots/debian buster stable' > /etc/apt/sources.list.d/belledonne.list \
    && wget https://linphone.org/snapshots/debian/keyring.gpg -O - | apt-key add - \
    && apt-get update \
    && apt-get install -y \
        libmariadb-dev \
        bc-flexisip=2.1.5-1 \
    && apt-get remove -y \
        gnupg2 \
        wget \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/* \
    && addgroup --system --gid 991 asterisk \
    && adduser --system --uid 990 --shell /bin/false --home /var/lib/asterisk --gecos 'Asterisk User' --ingroup asterisk asterisk \
    && mkdir -p /etc/flexisip/tls \
    && chown asterisk:asterisk /etc/flexisip \
    && mkdir -p /etc/asterisk \
    && chown asterisk:asterisk /etc/asterisk \
    && ln -sf /dev/stdout /var/log/flexisip.log

COPY entrypoint.sh /entrypoint
COPY usr/local/bin/import-certificate /usr/local/bin/import-certificate
ENTRYPOINT ["/entrypoint"]
CMD ["/opt/belledonne-communications/bin/flexisip"]
