FROM docker.io/library/debian:buster-slim as production

RUN apt-get update && apt-get install -y wget gnupg2
RUN echo 'deb [arch=amd64] http://linphone.org/snapshots/debian bullseye stable' > /etc/apt/sources.list.d/belledonne.list
RUN wget https://linphone.org/snapshots/debian/keyring.gpg -O - | apt-key add -
RUN apt-get update && apt-get install -y libmariadb-dev && apt-get install -y bc-flexisip
RUN apt-get -y remove wget gnupg2 && apt -y autoremove && apt-get -y clean

RUN addgroup --system --gid 991 asterisk && adduser --system --uid 990 --shell /bin/false --home /var/lib/asterisk --gecos 'Asterisk User' --ingroup asterisk asterisk
RUN mkdir -p /etc/flexisip/tls && chown asterisk:asterisk /etc/flexisip

COPY entrypoint.sh /entrypoint
ENTRYPOINT ["/entrypoint"]
CMD ["/opt/belledonne-communications/bin/flexisip", "--server", "proxy", "--syslog"]
