#!/bin/bash

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e 
# redirect output to stder
exec 1>&2

# copy passwords.env to passwords.old to keep old passwords
/usr/bin/cp passwords.env passwords.old

# start mariadb service
/usr/bin/systemctl --user start mariadb.service

# regenerate the secrets
runagent ../actions/create-module/05setenvs
