#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

# Start the MariaDB service
agent.run_helper(*'systemctl --user start mariadb.service'.split()).check_returncode()
