#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent

# old and new password for MARIADB_ROOT_PASSWORD
MARIADB_ROOT_PASSWORD_NEW = agent.read_envfile("passwords.env")['MARIADB_ROOT_PASSWORD']
MARIADB_ROOT_PASSWORD_OLD = agent.read_envfile("passwords.old")['MARIADB_ROOT_PASSWORD']

# Set new mariadb root password
SQL_QUERY = f"""
ALTER USER 'root'@'localhost' IDENTIFIED BY '{MARIADB_ROOT_PASSWORD_NEW}';
ALTER USER 'root'@'%' IDENTIFIED BY '{MARIADB_ROOT_PASSWORD_NEW}';
FlUSH PRIVILEGES;
"""
agent.run_helper(*f'podman exec mariadb mysql -u root -p{MARIADB_ROOT_PASSWORD_OLD} -e'.split(), SQL_QUERY).check_returncode()

# Set the new passwords
agent.run_helper(*f'podman exec --env-file="passwords.env" mariadb /docker-entrypoint-initdb.d/90_users.sh'.split()).check_returncode()
