#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

# Read the source environment file
env_clone = agent.read_envfile('environment.clone-module')

# Set new mariadb root password
SQL_QUERY = f"""
ALTER USER 'root'@'localhost' IDENTIFIED BY '{os.environ['MARIADB_ROOT_PASSWORD']}';
ALTER USER 'root'@'%' IDENTIFIED BY '{os.environ['MARIADB_ROOT_PASSWORD']}';
FlUSH PRIVILEGES;
"""
agent.run_helper(*f'podman exec mariadb mysql -u root -p{env_clone["MARIADB_ROOT_PASSWORD"]} -e'.split(), SQL_QUERY).check_returncode()

# Set the new passwords
agent.run_helper(*f'podman exec -e AMPDBPASS={os.environ["AMPDBPASS"]} mariadb /docker-entrypoint-initdb.d/90_users.sh'.split()).check_returncode()
