#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import random
import string

import agent

# rtp span port for Janus and Asterisk
span=2000
# coma separated port list
port_list = []
port_range = os.environ['TCP_PORTS_RANGE'].split("-")

# non-rtp ports
base_ports=int(port_range[1]) - int(port_range[0]) + 1

for i in range(int(port_range[0]), int(port_range[0]) + base_ports):
    port_list.append(i)

sip_start = int(port_range[0]) + base_ports
janus_start=sip_start + span
sip_end = sip_start + span -1
janus_end=int(port_range[1])

agent.set_env('NETHVOICE_MARIADB_PORT',port_list[0])
agent.set_env('APACHE_PORT',port_list[1])
agent.set_env('ASTMANAGERPORT',port_list[2])
agent.set_env('TANCREDIPORT',port_list[3])
agent.set_env('JANUS_TRANSPORT_PORT',port_list[4])
agent.set_env('NETHCTI_UI_PORT', port_list[5])
agent.set_env('NETHCTI_SERVER_API_PORT', port_list[6])
agent.set_env('NETHCTI_SERVER_WS_PORT', port_list[7])
agent.set_env('PHONEBOOK_LDAP_PORT', port_list[8])
agent.set_env('NETHCTI_INTERNAL_REST_PORT1', port_list[9])
agent.set_env('NETHCTI_INTERNAL_REST_PORT2', port_list[10])
agent.set_env('NETHCTI_INTERNAL_REST_PORT3', port_list[11])
agent.set_env('NETHCTI_INTERNAL_REST_PORT4', port_list[12])
agent.set_env('NETHCTI_INTERNAL_REST_PORT5', port_list[13])
agent.set_env('NETHCTI_INTERNAL_REST_PORT6', port_list[14])
agent.set_env('NETHCTI_INTERNAL_REST_PORT7', port_list[15])
agent.set_env('NETHCTI_INTERNAL_REST_PORT8', port_list[16])
agent.set_env('NETHCTI_INTERNAL_REST_PORT9', port_list[17])
agent.set_env('NETHCTI_INTERNAL_REST_PORT10', port_list[18])
agent.set_env('NETHCTI_INTERNAL_REST_PORT11', port_list[19])
agent.set_env('NETHCTI_INTERNAL_REST_PORT12', port_list[20])
agent.set_env('NETHCTI_INTERNAL_REST_PORT13', port_list[21])
agent.set_env('NETHCTI_TCP_PORT', port_list[22])
agent.set_env('NETHCTI_TLS_PORT', port_list[23])
agent.set_env('ASTERISK_SIP_PORT', port_list[24])
agent.set_env('ASTERISK_SIPS_PORT', port_list[25])
agent.set_env('ASTERISK_IAX_PORT', port_list[26])

# Set root password for MariaDB
agent.set_env('MARIADB_ROOT_PASSWORD',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(32)))

# Set DB configuration variables
agent.set_env('AMPDBUSER','freepbxuser')
agent.set_env('AMPDBHOST','127.0.0.1')
agent.set_env('AMPDBNAME','asterisk')
agent.set_env('AMPDBENGINE','mysql')
agent.set_env('AMPDBPASS',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(32)))
agent.set_env('AMPMGRUSER','asterisk')
agent.set_env('AMPMGRPASS',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(32)))
agent.set_env('APACHE_RUN_USER','asterisk')
agent.set_env('APACHE_RUN_GROUP','asterisk')
agent.set_env('AMPASTERISKWEBGROUP','asterisk')
agent.set_env('AMPASTERISKWEBUSER','asterisk')
agent.set_env('NETHCTI_AMI_PASSWORD', ''.join(random.choice(string.ascii_letters+string.digits) for _ in range(32)))

agent.set_env('BRAND_NAME','NethVoice')
agent.set_env('BRAND_SITE','http://www.nethvoice.it')
agent.set_env('BRAND_DOCS','http://nethvoice.docs.nethesis.it')

agent.set_env('CDRDBHOST','127.0.0.1')
agent.set_env('CDRDBNAME','asteriskcdrdb')
agent.set_env('CDRDBUSER','cdruser')
agent.set_env('CDRDBPASS',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(32)))

agent.set_env('NETHCTI_DB_HOST', '127.0.0.1')
agent.set_env('NETHCTI_DB_PORT', port_list[0])
agent.set_env('NETHCTI_DB_USER', 'nethcti3')
agent.set_env('NETHCTI_DB_PASSWORD',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(32)))

agent.set_env('TANCREDI_STATIC_TOKEN',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(32)))
agent.set_env('NETHVOICESECRETKEY',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(32)))

agent.set_env('JANUS_ADMIN_SECRET',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(32)))
agent.set_env('JANUS_DEBUG_LEVEL',5)
agent.set_env('JANUS_RTPSTART',janus_start)
agent.set_env('JANUS_RTPEND',janus_end)
agent.set_env('ASTERISK_RTPSTART',sip_start)
agent.set_env('ASTERISK_RTPEND',sip_end)
agent.set_env('STUNSERVER','stun1.l.google.com')
agent.set_env('STUNPORT',19302)
agent.set_env('ICEIGNORE','vmnet,tap,tun,virb,vb-')
agent.set_env('LOCAL_IP','172.25.5.83')

agent.set_env('TRAEFIK_HTTP2HTTPS','True')

agent.set_env('PHONEBOOK_DB_HOST','127.0.0.1')
agent.set_env('PHONEBOOK_DB_PORT',port_list[0])
agent.set_env('PHONEBOOK_DB_NAME','phonebook')
agent.set_env('PHONEBOOK_DB_USER','pbookuser')
agent.set_env('PHONEBOOK_DB_PASS',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(32)))
agent.set_env('PHONEBOOK_DB_USER','pbookuser')
agent.set_env('PHONEBOOK_LDAP_USER','ldapuser')
agent.set_env('PHONEBOOK_LDAP_PASS',''.join(random.choice(string.ascii_letters+string.digits) for _ in range(32)))
agent.set_env('PHONEBOOK_LDAP_LIMIT','500')
