#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os

import agent

agent.add_public_service(os.environ['MODULE_ID'], [
    os.environ['NETHCTI_TLS_PORT']+"/tcp", # NethCTI TLS (Nethifier)
    os.environ['RTPSTART']+"-"+os.environ['RTPEND']+"/tcp", # Janus
])

# Ignore exit code
