#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import subprocess
import os
import sys
import agent

counter_script=f"""
podman exec mariadb mariadb {os.environ['AMPDBNAME']}  -uroot  -p{os.environ['MARIADB_ROOT_PASSWORD']} -BN \
  -e "SELECT COUNT(*) FROM userman_users WHERE default_extension != 'none' UNION ALL SELECT COUNT(*) FROM rest_devices_phones WHERE type = 'mobile';"
"""

nethvoice_users = {}

try:
    with subprocess.Popen(counter_script, stdout=subprocess.PIPE, shell=True, text=True) as fcounter:
        res = fcounter.stdout.read().split('\n')
        nethvoice_users['nethvoice_users_count'] = int(res[0])
        nethvoice_users['nethvoice_mobile_users_count'] = int(res[1])

except Exception as ex:
    print(agent.SD_ERR, ex, file=sys.stderr)

json.dump(nethvoice_users, fp=sys.stdout)
