#!/bin/bash

# Dummy Asterisk executable for FreePBX

# Launch reload command using php
if [[ $1 == '-rx' && $2 = 'core reload' ]]; then
	php -r 'include_once "/etc/freepbx.conf"; global $astman; $astman->send_request("Reload");'
	exit 0
fi

# Output Asterisk version by default
echo 'Asterisk 18.12.1 built by makerpms @ b116.nethserver.org on a x86_64 running Linux on 2022-07-04 13:07:29 UTC'
