#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

if os.getenv('NETHVOICE_HOST') is None:
    print(agent.SD_DEBUG + "Event ignored: NethVoice is not configured")
    sys.exit(2)

event = json.load(sys.stdin)

if event['domain'] != os.environ['USER_DOMAIN']:
    print(agent.SD_DEBUG + "Event ignored: domain mismatch")
    sys.exit(3)
