#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os


# Set the proxy IP and port if not already set and the proxy is installed
if os.getenv('PROXY_IP') is None or os.getenv('PROXY_PORT') is None:
    proxy_id = agent.resolve_agent_id('nethvoice-proxy@node')
    if proxy_id is not None:
        ksrv = agent.list_service_providers(agent.redis_connect(use_replica=True), "sip", "tcp", {"module_id": proxy_id.removeprefix("module/")})
        agent.set_env("PROXY_IP", ksrv[0]["host"])
        agent.set_env("PROXY_PORT", ksrv[0]["port"])
