#!/bin/bash

# reload systemd changes
systemctl --user daemon-reload

# try to restart all services if they are running
systemctl --user try-restart flexisip freepbx janus mariadb nethcti-server nethcti-ui phonebook redis-flexisip reports-api reports-redis reports-ui tancredi
