#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys

import agent
import agent.tasks

# Find default traefik instance for current node
default_traefik_id = agent.resolve_agent_id('traefik@node')
if default_traefik_id is None:
    sys.exit(2)

services = [
    "wizard",
    "freepbx",
    "tancredi",
    "provisioning",
    "ui",
    "server-api",
    "server-websocket",
    "janus",
    "reports-api",
    "reports-ui",
    "users-admin",
    "cti-server-api",
]

# Remove traefik route
for service in services:
    response = agent.tasks.run(
        agent_id=default_traefik_id,
        action='delete-route',
        data={
            'instance': f"{os.environ['MODULE_ID']}-{service}"
        },
    )
    # Check if traefik configuration has been successfull
    agent.assert_exp(response['exit_code'] == 0)
