#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json

import agent
import agent.tasks

data = json.load(sys.stdin)
lets_encrypt = data.get("lets_encrypt", 'false')

agent.set_env('TRAEFIK_LETS_ENCRYPT', lets_encrypt)

# Find default traefik instance for current node
proxy_id = agent.resolve_agent_id('nethvoice-proxy@node')
if proxy_id is None:
    print("WARNING: No proxy found, skipping", file=sys.stderr)
    sys.exit(0)

print(f"Proxy id: {proxy_id}", file=sys.stderr) # debug

# Remove nethvoice-proxy route
if "NETHVOICE_HOST" not in os.environ:
    print("WARNING: No hostname configured, skipping proxy's route remove", file=sys.stderr)
    sys.exit(0)

response = agent.tasks.run(
    agent_id=proxy_id,
    action='remove-route',
    data={
        'domain': os.environ["NETHVOICE_HOST"],
    },
)

# Check if proxy configuration has been successfull
agent.assert_exp(response['exit_code'] == 0)
