#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys

import agent

request = json.load(sys.stdin)

# read from  the passwords.env file
passwordsfile = agent.read_envfile("passwords.env")

# PHONEBOOK_DB_PASS from migration
if "phonebook_db_password" in request:
    passwordsfile['PHONEBOOK_DB_PASS'] = request.get('phonebook_db_password', "")
    agent.write_envfile("passwords.env", passwordsfile)
