#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys

import agent

request = json.load(sys.stdin)

# PHONEBOOK_DB_PASS from migration
if "phonebook_db_password" in request:
    agent.set_env('PHONEBOOK_DB_PASS', request["phonebook_db_password"])
