#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

# check if there are mysql databases to migrate
# restore astdb
podman run \
    --rm \
    --name=restore_astdb \
    --volume=astdb:/var/lib/asterisk/db:z \
    --volume=./restore:/backup:z \
    "${NETHVOICE_FREEPBX_IMAGE}" \
    su -c "rm -fr /var/lib/asterisk/db/astdb.sqlite3; sqlite3 /var/lib/asterisk/db/astdb.sqlite3 < /backup/astdb.sqlite3.dump" -s /bin/bash asterisk

# remove astdb dump 
rm -f ./restore/astdb.sqlite3.dump