#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

# Add users, fixes and permissions
cat - > ./restore/99permissions.sh <<'EOF'
#!/bin/bash
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} asterisk -e 'DELETE FROM `kvstore_Sipsettings` WHERE `key`="udpport-0.0.0.0" OR `key`="tlsport-0.0.0.0" OR `key`="tcpport-0.0.0.0" OR `key`="bindport" OR `key`="tlsbindport"'
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} asterisk -e 'DELETE FROM `freepbx_settings` WHERE `keyword`="ASTMANAGERPORT" OR `keyword`="HTTPTLSENABLE"'
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} asterisk -e 'DELETE FROM `iaxsettings` WHERE `keyword`="bindport"'
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} asterisk -e 'DELETE FROM `sipsettings` WHERE `keyword`="bindport"'
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} nethcti3 -e 'DELETE FROM `user_dbconn` WHERE `name`="phonebook" OR `name`="asteriskcdrdb"'
sip_sql='INSERT INTO `kvstore_Sipsettings` (`key`,`val`,`type`,`id`) VALUES ("udpport-0.0.0.0","'${ASTERISK_SIP_PORT}'",NULL,"noid"), ("tlsport-0.0.0.0","'${ASTERISK_SIPS_PORT}'",NULL,"noid"), ("tcpport-0.0.0.0","'${ASTERISK_SIP_PORT}'",NULL,"noid");'
astmanager_sql='INSERT INTO `freepbx_settings` (`keyword`,`value`,`name`,`level`,`description`,`type`,`options`,`defaultval`,`readonly`,`hidden`,`category`,`module`,`emptyok`,`sortorder`) VALUES ("ASTMANAGERPORT","'${ASTMANAGERPORT}'","Asterisk Manager Port",2,"Port for the Asterisk Manager","int","1024,65535","'${ASTMANAGERPORT}'",1,0,"Asterisk Manager","",0,0);'
pjsip_sql='INSERT INTO `kvstore_Sipsettings` (`key`,`val`,`type`,`id`) VALUES ("bindport","'${ASTERISK_SIP_PORT}'",NULL,"noid"),("tlsbindport","'${ASTERISK_SIPS_PORT}'",NULL,"noid");'
# avoid listening on default 4569 port even if IAX is not configured
iax_sql_hack='INSERT INTO `iaxsettings` (`keyword`,`data`,`seq`,`type`) VALUES ("bindport","'${ASTERISK_IAX_PORT}'",1,0)'
# avoid listening on default 5060 port even if SIP is not configured
# this will cause a warning like: Failed to bind to 0.0.0.0:32120: Address already in use
sip_sql_hack='INSERT INTO `sipsettings` VALUES ("bindport","'${ASTERISK_SIP_PORT}'",1,0)'
# do not listen on port 8089
http_sql_hack='INSERT INTO `freepbx_settings` (`keyword`,`value`,`name`,`level`,`description`,`type`,`options`,`defaultval`,`readonly`,`hidden`,`category`,`module`,`emptyok`,`sortorder`) VALUES ("HTTPTLSENABLE","0","Enable TLS for the mini-HTTP Server",3,"Enables listening for HTTPS connections. This is for Asterisk, it is not directly related for FreePBX usage and the value of this setting is irrelevant for accessing core FreePBX settings. Default is no.","bool","","0",0,0,"Asterisk Builtin mini-HTTP server","",0,0)'
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} asterisk -e "$sip_sql"
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} asterisk -e "$pjsip_sql"
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} asterisk -e "$astmanager_sql"
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} asterisk -e "$sip_sql_hack"
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} asterisk -e "$iax_sql_hack"
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} asterisk -e "$http_sql_hack"
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} asterisk -e 'UPDATE sipsettings SET data="" WHERE keyword="externip_val"'
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} asterisk -e 'UPDATE kvstore_Sipsettings SET val="" WHERE `key`="externip"'
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} asterisk -e 'DELETE FROM kvstore_Sipsettings WHERE `key`="localnets"'
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} nethcti3 -e 'INSERT INTO user_dbconn (`id`,`host`,`port`,`type`,`user`,`pass`,`name`,`creation`) VALUES (1,"127.0.0.1","'${NETHVOICE_MARIADB_PORT}'","mysql","'${NETHCTI_DB_USER}'","'${NETHCTI_DB_PASSWORD}'","phonebook",NOW())'
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} nethcti3 -e 'INSERT INTO user_dbconn (`id`,`host`,`port`,`type`,`user`,`pass`,`name`,`creation`) VALUES (2,"127.0.0.1","'${NETHVOICE_MARIADB_PORT}'","mysql","'${AMPDBUSER}'","'${AMPDBPASS}'","asteriskcdrdb",NOW())'
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} -e "GRANT ALL on asterisk.* to '${AMPDBUSER}'@'127.0.0.1' identified by '${AMPDBPASS}'"
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} -e "GRANT ALL on asteriskcdrdb.* to '${AMPDBUSER}'@'127.0.0.1' identified by '${AMPDBPASS}'"
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} -e "GRANT ALL on asteriskcdrdb.* to '${CDRDBUSER}'@'127.0.0.1' identified by '${CDRDBPASS}'"
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} -e "GRANT ALL on nethcti3.* to '${NETHCTI_DB_USER}'@'127.0.0.1' identified by '${NETHCTI_DB_PASSWORD}'"
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} -e "GRANT ALL on ${PHONEBOOK_DB_NAME}.* to '${PHONEBOOK_DB_USER}'@'127.0.0.1' identified by '${PHONEBOOK_DB_PASS}'"
/usr/bin/mysql -uroot -p${MARIADB_ROOT_PASSWORD} -e "GRANT SELECT on ${PHONEBOOK_DB_NAME}.* to '${NETHCTI_DB_USER}'@'127.0.0.1' identified by '${NETHCTI_DB_PASSWORD}'"
/usr/bin/mysql -uroot -p"${MARIADB_ROOT_PASSWORD}" -e "GRANT ALL on asteriskcdrdb.* to 'nethvoice_report'@'%' identified by '${REPORTS_PASSWORD}';"
/usr/bin/mysql -uroot -p"${MARIADB_ROOT_PASSWORD}" -e "GRANT ALL on asteriskcdrdb.* to 'nethvoice_report'@'localhost' identified by '${REPORTS_PASSWORD}';"
/usr/bin/mysql -uroot -p"${MARIADB_ROOT_PASSWORD}" -e "GRANT ALL on asterisk.* to 'nethvoice_report'@'%' identified by '${REPORTS_PASSWORD}';"
/usr/bin/mysql -uroot -p"${MARIADB_ROOT_PASSWORD}" -e "GRANT ALL on asterisk.* to 'nethvoice_report'@'localhost' identified by '${REPORTS_PASSWORD}';"
/usr/bin/mysql -uroot -p"${MARIADB_ROOT_PASSWORD}" -e "GRANT SELECT on phonebook.* to 'nethvoice_report'@'%' identified by '${REPORTS_PASSWORD}';"
/usr/bin/mysql -uroot -p"${MARIADB_ROOT_PASSWORD}" -e "GRANT SELECT on phonebook.* to 'nethvoice_report'@'localhost' identified by '${REPORTS_PASSWORD}';"
EOF

# Add script that kill the temporary server
cat - > ./restore/zz_restore.sh <<EOF
#!/bin/bash
set -e
mysql --version
set -- true
docker_temp_server_stop
exit 0
EOF

# launch a temporary server for restore the migration dumps
podman run \
    --rm \
    --interactive \
    --name=mariadb_migration \
    --network=none \
    --volume=./restore:/docker-entrypoint-initdb.d:z \
    --volume=mariadb-data:/var/lib/mysql:Z \
    --env=MARIADB_ROOT_PASSWORD \
    --env=NETHVOICE_MARIADB_PORT \
    --env=AMPDBUSER \
    --env=AMPDBPASS \
    --env=CDRDBUSER \
    --env=CDRDBHOST \
    --env=CDRDBPASS \
    --env=CTIUSER \
    --env=NETHCTI_DB_USER \
    --env=NETHCTI_DB_PASSWORD \
    --env=PHONEBOOK* \
    --env=ASTERISK_RTPSTART \
    --env=ASTERISK_RTPEND \
    --env=ASTERISK_SIP_PORT \
    --env=ASTERISK_SIPS_PORT \
    --env=ASTERISK_IAX_PORT \
    --env=ASTMANAGERPORT \
    --env=REPORTS_PASSWORD \
    --env=MARIADB_AUTO_UPGRADE=1 \
    "${NETHVOICE_MARIADB_IMAGE}"
