#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os

import agent

config = {
    'nethvoice_host': os.getenv('NETHVOICE_HOST', ''),
    'nethcti_ui_host': os.getenv('NETHCTI_UI_HOST', ''),
    'lets_encrypt': os.getenv('TRAEFIK_LETS_ENCRYPT') == 'True',
    'timezone': os.getenv('TIMEZONE', 'UTC'),
    'user_domain': os.getenv('USER_DOMAIN', ''),
    'reports_international_prefix': os.getenv('REPORTS_INTERNATIONAL_PREFIX', ''),
    'nethvoice_adm_username': os.getenv('NETHVOICE_USER_PORTAL_USERNAME', ''),
    'nethvoice_adm_password': agent.read_envfile("passwords.env").get('NETHVOICE_USER_PORTAL_PASSWORD',""),
    'nethcti_privacy_numbers': os.getenv('NETHCTI_PRIVACY_NUMBERS', 'xxx'),
}

json.dump(config, fp=sys.stdout)
