#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os
import requests

import agent
request = json.load(sys.stdin)

def getFromRequest(request, var_name, env_name, default = ""):
    if var_name in request:
        agent.set_env(env_name, request[var_name])
    else:
        agent.set_env(env_name, default)

# get system id
rdb = agent.redis_connect(privileged=False)
subscription = rdb.hgetall('cluster/subscription')

# check if system has a key
if 'system_id' in subscription:
    key = subscription['system_id']

    # call rebranding api
    url = f'https://my.nethesis.it/api/systems/rebranding/{key}'
    data = requests.get(url).json()

    # check if rebrand is active
    if 'brand' in data:
        getFromRequest(request, 'rebranding_login_people', 'LOGIN_PEOPLE', '')

        getFromRequest(request, 'rebranding_navbar_logo_url', 'NAVBAR_LOGO_URL', '')
        getFromRequest(request, 'rebranding_navbar_logo_dark_url', 'NAVBAR_LOGO_DARK_URL', '')
        getFromRequest(request, 'rebranding_login_logo_url', 'LOGIN_LOGO_URL', '')
        getFromRequest(request, 'rebranding_login_logo_dark_url', 'LOGIN_LOGO_DARK_URL', '')

        getFromRequest(request, 'rebranding_favicon_url', 'FAVICON_URL', '')

        getFromRequest(request, 'rebranding_login_background_url', 'LOGIN_BACKGROUND_URL', '')

        # try to restart the service if needed
        agent.run_helper(*'systemctl --user try-restart nethcti-ui.service'.split()).check_returncode()