FROM docker.io/library/node:14.21.1-alpine as base
WORKDIR /app

FROM base as node_modules
RUN apk add --no-cache \
        python3 \
        make
COPY usr/lib/node/nethcti-server/package.json .
COPY usr/lib/node/nethcti-server/package-lock.json .
RUN npm ci

FROM base as production
RUN apk add --no-cache openldap-clients
RUN groupadd -g 991 -r asterisk && useradd -u 990 -r -s /bin/false -d /var/lib/asterisk -M -c 'Asterisk User' -g asterisk asterisk
RUN mkdir -p /etc/nethcti && chown asterisk:asterisk /etc/nethcti
COPY var/lib/nethserver/nethcti/templates/customer_card /var/lib/nethserver/nethcti/templates/customer_card
COPY usr/lib/node/nethcti-server/plugins plugins
COPY usr/lib/node/nethcti-server/scripts scripts
COPY usr/lib/node/nethcti-server/sql sql
COPY usr/lib/node/nethcti-server/nethcti-cli.js .
COPY usr/lib/node/nethcti-server/nethcti.js .
COPY usr/local/bin/rpm /usr/local/bin/rpm
COPY --from=node_modules /app/package.json .
COPY --from=node_modules /app/package-lock.json .
COPY --from=node_modules /app/node_modules node_modules
COPY entrypoint.sh /entrypoint
ENTRYPOINT ["/entrypoint"]
CMD ["npm", "start"]
