# Stage 1: Build Asterisk
FROM docker.io/debian:11 as builder

# Set fixed Asterisk version
ARG ASTERISK_VERSION=18.22.0
ARG PJSIP_VERSION=2.13.1
ARG DEBIAN_FRONTEND=noninteractive
ARG BUILDROOT=/usr/src/asterisk/build
ARG LIBDIR=/usr/lib
ARG DATADIR=/var/lib
ARG MAKEARGS="DEBUG= OPTIMIZE= DESTDIR=${BUILDROOT} ASTVARRUNDIR=/var/run/asterisk ASTDATADIR=${DATADIR}/asterisk ASTVARLIBDIR=${DATADIR}/asterisk ASTDBDIR=${DATADIR}/asterisk/db NOISY_BUILD=1"
COPY usr/src/asterisk /usr/src/asterisk
RUN apt-get update && \
	apt-get install -y \
		automake \
		build-essential \
		doxygen \
		graphviz \
		libasound2-dev \
		libcap-dev \
		libcurl4-openssl-dev \
		libedit-dev \
		libgcrypt20-dev \
		libgmime-3.0-dev \
		libgsm1-dev \
		libical-dev \
		libjansson-dev \
		libjpeg62-turbo-dev \
		libldap2-dev \
		libltdl-dev \
		liblua5.3-dev \
		libmariadb-dev \
		libncursesw5-dev \
		libneon27-dev \
		libnewt-dev \
		libogg-dev \
		libpopt-dev \
		libpq-dev \
		libpri-dev \
		libresample1-dev \
		libsdl1.2-dev \
		libsdl-image1.2-dev \
		libsensors4-dev \
		libsnmp-dev \
		libspandsp-dev \
		libspeex-dev \
		libspeexdsp-dev \
		libsqlite3-dev \
		libsrtp2-dev \
		libss7-dev \
		libssl-dev \
		libsybdb5 \
		libtiff5-dev \
		libunbound-dev \
		libvorbis-dev \
		libxslt1-dev \
		make \
		ncurses-bin \
		portaudio19-dev \
		unixodbc-dev \
		uuid-dev \
		wget

RUN cd /usr/src/asterisk && \
	wget https://downloads.asterisk.org/pub/telephony/asterisk/old-releases/asterisk-${ASTERISK_VERSION}.tar.gz && \
	tar xzf asterisk-${ASTERISK_VERSION}.tar.gz && \
	rm -f asterisk-${ASTERISK_VERSION}.tar.gz && \
	mkdir cache && \
	cd cache && \
	wget https://raw.githubusercontent.com/asterisk/third-party/master/pjproject/${PJSIP_VERSION}/pjproject-${PJSIP_VERSION}.tar.bz2 && \
	cd .. && \
	cd asterisk-${ASTERISK_VERSION} && \
	patch -p1 < ../asterisk-18-mp3.patch && \
	patch -p1 < ../lazymembers.patch && \
	mv ../menuselect.make* ./ && \
	perl -pi -e 's/^all:.*$/all:/' sounds/Makefile && \
	perl -pi -e 's/^install:.*$/install:/' sounds/Makefile && \
	mv main/fskmodem.c main/fskmodem.c.old && \
	iconv -f iso-8859-1 -t utf-8 -o main/fskmodem.c main/fskmodem.c.old	&& \
	touch -r main/fskmodem.c.old main/fskmodem.c && \
	rm main/fskmodem.c.old && \
	chmod -x contrib/scripts/dbsep.cgi && \
	export CFLAGS=" -Werror-implicit-function-declaration -DLUA_COMPAT_MODULE -fPIC" && \
	export CXXFLAGS="-Werror-implicit-function-declaration -DLUA_COMPAT_MODULE -fPIC" && \
	export FFLAGS="-Werror-implicit-function-declaration -DLUA_COMPAT_MODULE -fPIC" && \
	export LDFLAGS="-m64 -Wl,--as-needed,--library-path=/usr/lib/x86_64-linux-gnu" && \
	export ASTCFLAGS=" " && \
	sed -i '1s/env python/python3/' contrib/scripts/refcounter.py && \
	./bootstrap.sh && \
	cd menuselect && \
	./configure && \
	cd .. && \
	mkdir -p \
		${BUILDROOT}${DATADIR}/asterisk/.gnupg \
		${BUILDROOT}${DATADIR}/asterisk/agi-bin \
		${BUILDROOT}${DATADIR}/asterisk/db \
		${BUILDROOT}${DATADIR}/asterisk/images \
		${BUILDROOT}${DATADIR}/asterisk/keys/stir_shaken \
		${BUILDROOT}${DATADIR}/asterisk/moh \
		${BUILDROOT}${DATADIR}/asterisk/sounds \
		${BUILDROOT}/var/spool/asterisk/outgoing \
		${BUILDROOT}/var/spool/asterisk/uploads \
		${BUILDROOT}/var/spool/asterisk/cache && \
	./configure --without-imap --with-externals-cache=/usr/src/asterisk/cache --with-gsm=/usr --without-ilbc --with-libedit=yes --with-srtp --with-jansson-bundled --with-pjproject-bundled --with-libjwt-bundled LDFLAGS="${LDFLAGS}" NOISY_BUILD=1 CPPFLAGS="-fPIC" && \
	make menuselect-tree && \
	perl -n -i -e 'print unless /openr2/i' menuselect-tree && \
	make ${MAKEARGS} && \
	make install ${MAKEARGS} && \
	make samples ${MAKEARGS} && \
	install -D -p -m 0755 apps/app_voicemail_odbc.so ${BUILDROOT}${LIBDIR}/asterisk/modules/app_voicemail_odbc.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/libasteriskssl.so && \
	ln -s libasteriskssl.so.1 ${BUILDROOT}${LIBDIR}/libasteriskssl.so && \
	rm -rf ${BUILDROOT}/etc/asterisk/* && \
	rm -rf ${BUILDROOT}/var/lib/asterisk/phoneprov/* && \
	rm -rf ${BUILDROOT}/tmp && \
	rm -rf ${BUILDROOT}/var/spool/asterisk/voicemail/default && \
	# Remove unused modules
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/app_adsiprog.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/app_festival.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/app_getcpeid.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/app_ices.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/app_image.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/app_jack.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/app_nbscat.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/app_url.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/app_voicemail.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/cdr_sqlite3_custom.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/cel_sqlite3_custom.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/chan_alsa.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/chan_console.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/chan_mgcp.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/chan_oss.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/chan_unistim.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/cdr_pgsql.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/cel_pgsql.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/chan_skinny.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/pbx_ael.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/pbx_lua.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/res_adsi.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/res_config_pgsql.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/res_hep.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/res_hep_rtcp.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/res_http_post.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/res_hep_pjsip.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/res_mwi_external.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/res_mwi_external_ami.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/res_pjsip_transport_websocket.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/res_pktccops.so && \
	rm -rf ${BUILDROOT}${LIBDIR}/asterisk/modules/res_stasis_mailbox.so && \
	cp -a contrib/ast-db-manage ${BUILDROOT}${DATADIR}/asterisk/ast-db-manage && \
	wget http://downloads.digium.com/pub/telephony/codec_opus/asterisk-18.0/x86-64/codec_opus-18.0_current-x86_64.tar.gz && \
	tar xzf codec_opus-18.0_current-x86_64.tar.gz --strip-components=1 && \
	wget http://downloads.digium.com/pub/telephony/codec_silk/asterisk-18.0/x86-64/codec_silk-18.0_current-x86_64.tar.gz && \
	tar xzf codec_silk-18.0_current-x86_64.tar.gz --strip-components=1 && \
	wget http://downloads.digium.com/pub/telephony/codec_siren7/asterisk-18.0/x86-64/codec_siren7-18.0_current-x86_64.tar.gz && \
	tar xzf codec_siren7-18.0_current-x86_64.tar.gz --strip-components=1 && \
	wget http://downloads.digium.com/pub/telephony/codec_siren14/asterisk-18.0/x86-64/codec_siren14-18.0_current-x86_64.tar.gz && \
	tar xzf codec_siren14-18.0_current-x86_64.tar.gz --strip-components=1 && \
	cp *.so ${BUILDROOT}${LIBDIR}/asterisk/modules/ && \
	cp codec_opus_config-en_US.xml ${BUILDROOT}${DATADIR}/asterisk/documentation/thirdparty/ && \
	wget -nv http://asterisk.hosting.lv/bin/codec_g729-ast180-gcc4-glibc-x86_64-pentium4.so -O ${BUILDROOT}${LIBDIR}/asterisk/modules/codec_g729.so


FROM docker.io/library/php:7.4-apache
WORKDIR /var/lib/asterisk
ARG DEBIAN_FRONTEND=noninteractive
RUN groupadd -g 991 -r asterisk && \
    useradd -u 990 -r -s /bin/false -d /var/lib/asterisk -M -c 'Asterisk User' -g asterisk asterisk && \
	apt-get update && \
	apt-get install -y \
		cron \
		tdsodbc \
		gettext \
		gnupg \
		jq \
		libldap2-dev \
		libldap-2.4-2 \
		libsodium-dev \
		logrotate \
		mpg123 \
		mycli \
		nodejs \
		npm \
		pip \
		python3-pycurl \
		python3-pyodbc \
		sox \
		zip \
		vim \
		supervisor \
		wget \
		odbc-mariadb \
		libjansson4 \
		openssl \
		libxml2 \
		libxslt1.1 \
		libsrtp2-1 \
		libspeex1 \
		libspeexdsp1 \
		libneon27 \
		libspandsp2 \
		libsnmp40 \
		libical3 \
		sqlite3 \
		s-nail \
		unixodbc-dev


# Copy Asterisk files
COPY --from=builder /usr/src/asterisk/build/./ /

RUN chown asterisk:asterisk \
	/var/lib/asterisk \
	/var/lib/asterisk/.gnupg \
	/var/lib/asterisk/agi-bin \
	/var/lib/asterisk/db \
	/var/lib/asterisk/sounds \
	/var/log/asterisk \
	/var/log/asterisk/cdr-csv \
	/var/log/asterisk/cdr-custom \
	/var/spool/asterisk/ \
	/var/spool/asterisk/monitor \
	/var/spool/asterisk/outgoing \
	/var/spool/asterisk/tmp \
	/var/spool/asterisk/uploads \
	/var/spool/asterisk/voicemail \
	/var/spool/asterisk/cache

RUN mkdir download \
    && cd download \
    && mkdir -p /var/lib/asterisk/sounds/nethcti \
    && wget -nv https://github.com/nethesis/ns8-nethvoice/releases/download/0.0.1-rc.2.0.2/asterisk-sounds-de.tar.gz \
    && wget -nv https://github.com/nethesis/ns8-nethvoice/releases/download/0.0.1-rc.2.0.2/asterisk-sounds-en.tar.gz \
    && wget -nv https://github.com/nethesis/ns8-nethvoice/releases/download/0.0.1-rc.2.0.2/asterisk-sounds-es.tar.gz \
    && wget -nv https://github.com/nethesis/ns8-nethvoice/releases/download/0.0.1-rc.2.0.2/asterisk-sounds-fr.tar.gz \
    && wget -nv https://github.com/nethesis/ns8-nethvoice/releases/download/0.0.1-rc.2.0.2/asterisk-sounds-it.tar.gz \
    && tar xzvf asterisk-sounds-de.tar.gz -C /var/lib/asterisk/sounds \
    && tar xzvf asterisk-sounds-en.tar.gz -C /var/lib/asterisk/sounds \
    && tar xzvf asterisk-sounds-es.tar.gz -C /var/lib/asterisk/sounds \
    && tar xzvf asterisk-sounds-fr.tar.gz -C /var/lib/asterisk/sounds \
    && tar xzvf asterisk-sounds-it.tar.gz -C /var/lib/asterisk/sounds \
    && chown -R asterisk:asterisk /var/lib/asterisk/sounds \
    && cd .. && rm -rf download

COPY --chown=asterisk:asterisk etc/asterisk /etc/asterisk
COPY etc/odbc.ini /etc/odbc.ini
COPY etc/odbcinst.ini /etc/odbcinst.ini
COPY var/lib/asterisk /var/lib/asterisk
COPY usr/bin/backup_astdb /usr/bin/backup_astdb
COPY usr/bin/restore_astdb /usr/bin/restore_astdb
COPY usr/local/bin/import-certificate /usr/local/bin/import-certificate

RUN mkdir -p \
	/etc/phonebook/sources.d/ \
	/var/lib/asterisk/playback \
	/var/run/asterisk/ \
	/var/run/nethvoice/ \
	/var/www/html/freepbx/admin/modules/framework

# Download framework module
RUN curl -L https://github.com/FreePBX/framework/archive/refs/tags/release/16.0.39.tar.gz | tar xzp --strip-component=1 -C /var/www/html/freepbx/admin/modules/framework && \
	cp -a /var/www/html/freepbx/admin/modules/framework/amp_conf/htdocs/* /var/www/html/freepbx/ && \
	cp /var/www/html/freepbx/admin/modules/framework/amp_conf/astetc/enum.conf /etc/asterisk/ && \
	cp /var/www/html/freepbx/admin/modules/framework/amp_conf/astetc/musiconhold.conf /etc/asterisk/ && \
	cp /var/www/html/freepbx/admin/modules/framework/amp_conf/astetc/phpagi.conf /etc/asterisk/ && \
	cp /var/www/html/freepbx/admin/modules/framework/amp_conf/astetc/privacy.conf /etc/asterisk/ && \
	cp /var/www/html/freepbx/admin/modules/framework/amp_conf/astetc/queues.conf /etc/asterisk/ && \
	cp /var/www/html/freepbx/admin/modules/framework/amp_conf/astetc/ucc_restrict.conf /etc/asterisk/ && \
	cp -a /var/www/html/freepbx/admin/modules/framework/amp_conf/agi-bin /var/lib/asterisk/ && \
	cp -a /var/www/html/freepbx/admin/modules/framework/amp_conf/bin /var/lib/asterisk/

# Download other modules
# for baseurl in $(grep wget retrieve_modules.sh | awk '{print $2}' | sed 's/archive.*/tags/'); do pkgurl=https://github.com$(curl $baseurl 2>/dev/null | grep '\.tar\.gz' | head -n1 | cut -d\" -f4) ; pkgname=$(echo $pkgurl | cut -d/ -f5 | tr '[:upper:]' '[:lower:]'); echo -e "RUN mkdir -p /var/www/html/freepbx/admin/modules/$pkgname && \\\n\t/bin/rm -fr /var/www/html/freepbx/admin/modules/$pkgname/* && \\\n\tcurl -sL $pkgurl -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/$pkgname"; done
RUN mkdir -p /var/www/html/freepbx/admin/modules/announcement && \
	curl -sL https://github.com/FreePBX/announcement/archive/refs/tags/release/16.0.6.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/announcement && \
	mkdir -p /var/www/html/freepbx/admin/modules/arimanager && \
	curl -sL https://github.com/FreePBX/arimanager/archive/refs/tags/release/16.0.12.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/arimanager && \
	mkdir -p /var/www/html/freepbx/admin/modules/asteriskinfo && \
	curl -sL https://github.com/FreePBX/asteriskinfo/archive/refs/tags/release/16.0.9.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/asteriskinfo && \
	mkdir -p /var/www/html/freepbx/admin/modules/backup && \
	curl -sL https://github.com/FreePBX/backup/archive/refs/tags/release/16.0.62.8.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/backup && \
	mkdir -p /var/www/html/freepbx/admin/modules/blacklist && \
	curl -sL https://github.com/FreePBX/blacklist/archive/refs/tags/release/16.0.20.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/blacklist && \
	mkdir -p /var/www/html/freepbx/admin/modules/bulkhandler && \
	curl -sL https://github.com/FreePBX/bulkhandler/archive/refs/tags/release/16.0.16.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/bulkhandler && \
	mkdir -p /var/www/html/freepbx/admin/modules/calendar && \
	curl -sL https://github.com/FreePBX/calendar/archive/refs/tags/release/16.0.21.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/calendar && \
	mkdir -p /var/www/html/freepbx/admin/modules/callback && \
	curl -sL https://github.com/FreePBX/callback/archive/refs/tags/release/16.0.4.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/callback && \
	mkdir -p /var/www/html/freepbx/admin/modules/callforward && \
	curl -sL https://github.com/FreePBX/callforward/archive/refs/tags/release/16.0.5.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/callforward && \
	mkdir -p /var/www/html/freepbx/admin/modules/callrecording && \
	curl -sL https://github.com/FreePBX/callrecording/archive/refs/tags/release/16.0.19.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/callrecording && \
	mkdir -p /var/www/html/freepbx/admin/modules/callwaiting && \
	curl -sL https://github.com/FreePBX/callwaiting/archive/refs/tags/release/16.0.5.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/callwaiting && \
	mkdir -p /var/www/html/freepbx/admin/modules/cdr && \
	curl -sL https://github.com/FreePBX/cdr/archive/refs/tags/release/16.0.30.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/cdr && \
	mkdir -p /var/www/html/freepbx/admin/modules/cel && \
	curl -sL https://github.com/FreePBX/cel/archive/refs/tags/release/16.0.13.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/cel && \
	mkdir -p /var/www/html/freepbx/admin/modules/certman && \
	curl -sL https://github.com/FreePBX/certman/archive/refs/tags/release/16.0.25.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/certman && \
	mkdir -p /var/www/html/freepbx/admin/modules/conferences && \
	curl -sL https://github.com/FreePBX/conferences/archive/refs/tags/release/16.0.9.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/conferences && \
	mkdir -p /var/www/html/freepbx/admin/modules/customappsreg && \
	curl -sL https://github.com/FreePBX/customappsreg/archive/refs/tags/release/16.0.5.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/customappsreg && \
	mkdir -p /var/www/html/freepbx/admin/modules/daynight && \
	curl -sL https://github.com/FreePBX/daynight/archive/refs/tags/release/16.0.3.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/daynight && \
	mkdir -p /var/www/html/freepbx/admin/modules/dashboard && \
	curl -sL https://github.com/FreePBX/dashboard/archive/refs/tags/release/16.0.16.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/dashboard && \
	mkdir -p /var/www/html/freepbx/admin/modules/disa && \
	curl -sL https://github.com/FreePBX/disa/archive/refs/tags/release/16.0.4.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/disa && \
	mkdir -p /var/www/html/freepbx/admin/modules/donotdisturb && \
	curl -sL https://github.com/FreePBX/donotdisturb/archive/refs/tags/release/16.0.3.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/donotdisturb && \
	mkdir -p /var/www/html/freepbx/admin/modules/fax && \
	curl -sL https://github.com/FreePBX/fax/archive/refs/tags/release/16.0.13.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/fax && \
	mkdir -p /var/www/html/freepbx/admin/modules/featurecodeadmin && \
	curl -sL https://github.com/FreePBX/featurecodeadmin/archive/refs/tags/release/16.0.11.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/featurecodeadmin && \
	mkdir -p /var/www/html/freepbx/admin/modules/filestore && \
	curl -sL https://github.com/FreePBX/filestore/archive/refs/tags/release/16.0.15.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/filestore && \
	mkdir -p /var/www/html/freepbx/admin/modules/findmefollow && \
	curl -sL https://github.com/FreePBX/findmefollow/archive/refs/tags/release/16.0.19.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/findmefollow && \
	mkdir -p /var/www/html/freepbx/admin/modules/framework && \
	curl -sL https://github.com/FreePBX/framework/archive/refs/tags/release/16.0.39.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/framework && \
	mkdir -p /var/www/html/freepbx/admin/modules/iaxsettings && \
	curl -sL https://github.com/FreePBX/iaxsettings/archive/refs/tags/release/16.0.3.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/iaxsettings && \
	mkdir -p /var/www/html/freepbx/admin/modules/infoservices && \
	curl -sL https://github.com/FreePBX/infoservices/archive/refs/tags/release/16.0.2.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/infoservices && \
	mkdir -p /var/www/html/freepbx/admin/modules/ivr && \
	curl -sL https://github.com/FreePBX/ivr/archive/refs/tags/release/16.0.5.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/ivr && \
	mkdir -p /var/www/html/freepbx/admin/modules/languages && \
	curl -sL https://github.com/FreePBX/languages/archive/refs/tags/release/16.0.4.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/languages && \
	mkdir -p /var/www/html/freepbx/admin/modules/logfiles && \
	curl -sL https://github.com/FreePBX/logfiles/archive/refs/tags/release/16.0.7.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/logfiles && \
	mkdir -p /var/www/html/freepbx/admin/modules/manager && \
	curl -sL https://github.com/FreePBX/manager/archive/refs/tags/release/16.0.17.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/manager && \
	mkdir -p /var/www/html/freepbx/admin/modules/miscapps && \
	curl -sL https://github.com/FreePBX/miscapps/archive/refs/tags/release/16.0.2.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/miscapps && \
	mkdir -p /var/www/html/freepbx/admin/modules/music && \
	curl -sL https://github.com/FreePBX/music/archive/refs/tags/release/16.0.2.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/music && \
	mkdir -p /var/www/html/freepbx/admin/modules/outroutemsg && \
	curl -sL https://github.com/FreePBX/outroutemsg/archive/refs/tags/release/16.0.1.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/outroutemsg && \
	mkdir -p /var/www/html/freepbx/admin/modules/parking && \
	curl -sL https://github.com/FreePBX/parking/archive/refs/tags/release/16.0.4.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/parking && \
	mkdir -p /var/www/html/freepbx/admin/modules/pm2 && \
	curl -sL https://github.com/FreePBX/pm2/archive/refs/tags/release/14.0.1.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/pm2 && \
	mkdir -p /var/www/html/freepbx/admin/modules/queueprio && \
	curl -sL https://github.com/FreePBX/queueprio/archive/refs/tags/release/16.0.3.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/queueprio && \
	mkdir -p /var/www/html/freepbx/admin/modules/ringgroups && \
	curl -sL https://github.com/FreePBX/ringgroups/archive/refs/tags/release/16.0.11.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/ringgroups && \
	mkdir -p /var/www/html/freepbx/admin/modules/setcid && \
	curl -sL https://github.com/FreePBX/setcid/archive/refs/tags/release/16.0.3.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/setcid && \
	mkdir -p /var/www/html/freepbx/admin/modules/sipsettings && \
	curl -sL https://github.com/FreePBX/sipsettings/archive/refs/tags/release/16.0.26.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/sipsettings && \
	mkdir -p /var/www/html/freepbx/admin/modules/soundlang && \
	curl -sL https://github.com/FreePBX/soundlang/archive/refs/tags/release/16.0.9.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/soundlang && \
	mkdir -p /var/www/html/freepbx/admin/modules/timeconditions && \
	curl -sL https://github.com/FreePBX/timeconditions/archive/refs/tags/release/16.0.10.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/timeconditions && \
	mkdir -p /var/www/html/freepbx/admin/modules/userman && \
	curl -sL https://github.com/FreePBX/userman/archive/refs/tags/release/16.0.44.9.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/userman && \
	mkdir -p /var/www/html/freepbx/admin/modules/vmblast && \
	curl -sL https://github.com/FreePBX/vmblast/archive/refs/tags/release/16.0.10.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/vmblast

# Download and install Nethesis modules
RUN mkdir -p /var/www/html/freepbx/admin/modules/bosssecretary && \
	curl -sL https://github.com/nethesis/freepbx-bosssecretary/archive/master.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/bosssecretary && \
	mkdir -p /var/www/html/freepbx/admin/modules/core && \
	/bin/rm -fr /var/www/html/freepbx/admin/modules/core/* && \
	curl -sL https://github.com/nethesis/freepbx-core/archive/refs/tags/release/ns8/16.0.68.9-pl.2.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/core && \
	mkdir -p /var/www/html/freepbx/admin/modules/customcontexts && \
	curl -sL https://github.com/nethesis/freepbx-customcontexts/archive/refs/tags/release/13.0.3.4.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/customcontexts && \
	mkdir -p /var/www/html/freepbx/admin/modules/directdid && \
	curl -sL https://github.com/nethesis/directdid/archive/1.1.8.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/directdid && \
	mkdir -p /var/www/html/freepbx/admin/modules/extraoptions && \
	curl -sL https://github.com/nethesis/freepbx-extraoptions/archive/master.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/extraoptions && \
	mkdir -p /var/www/html/freepbx/admin/modules/googletts && \
	curl -sL https://github.com/nethesis/googletts/archive/refs/tags/0.0.3.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/googletts && \
	mkdir -p /var/www/html/freepbx/admin/modules/nethdash && \
	curl -sL https://github.com/nethesis/nethdash/archive/1.0.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/nethdash && \
	mkdir -p /var/www/html/freepbx/admin/modules/paging && \
	curl -sL https://github.com/nethesis/freepbx-paging/archive/refs/tags/release/ns8/16.0.11-pl.2.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/paging && \
	mkdir -p /var/www/html/freepbx/admin/modules/queueexit && \
	curl -sL https://github.com/nethesis/queueexit/archive/0.0.1.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/queueexit && \
	mkdir -p /var/www/html/freepbx/admin/modules/queuemetrics && \
	curl -sL https://github.com/nethesis/queuemetrics/archive/refs/tags/release/2.11.0.3.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/queuemetrics && \
	mkdir -p /var/www/html/freepbx/admin/modules/queues && \
	curl -sL https://github.com/nethesis/freepbx-queues/archive/refs/heads/nethesis_nv8.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/queues && \
	mkdir -p /var/www/html/freepbx/admin/modules/rapidcode && \
	curl -sL https://github.com/nethesis/RapidCode/archive/refs/tags/1.0.1.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/rapidcode && \
	mkdir -p /var/www/html/freepbx/admin/modules/recordings && \
	curl -sL https://github.com/nethesis/freepbx-recordings/archive/refs/heads/nethesis_nv8.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/recordings && \
	mkdir -p /var/www/html/freepbx/admin/modules/returnontransfer && \
	curl -sL https://github.com/nethesis/returnontransfer/archive/refs/tags/1.1.10.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/returnontransfer && \
	mkdir -p /var/www/html/freepbx/admin/modules/voicemail && \
	curl -sL https://github.com/nethesis/freepbx-voicemail/archive/14.0.6.26.tar.gz -o - | tar xzp --strip-components=1 -C /var/www/html/freepbx/admin/modules/voicemail

# Install Nethesis vendor modules
COPY --chown=asterisk:asterisk var/www/html/freepbx/admin/modules/nethcqr /var/www/html/freepbx/admin/modules/nethcqr
COPY --chown=asterisk:asterisk var/www/html/freepbx/admin/modules/nethcti3 /var/www/html/freepbx/admin/modules/nethcti3
COPY --chown=asterisk:asterisk var/www/html/freepbx/admin/modules/pin /var/www/html/freepbx/admin/modules/pin
COPY --chown=asterisk:asterisk var/www/html/freepbx/admin/modules/queueoptions /var/www/html/freepbx/admin/modules/queueoptions
COPY --chown=asterisk:asterisk var/www/html/freepbx/admin/modules/recallonbusy /var/www/html/freepbx/admin/modules/recallonbusy
COPY usr/sbin/recallonbusy /usr/sbin/recallonbusy
COPY --chown=asterisk:asterisk var/www/html/freepbx/admin/modules/visualplan /var/www/html/freepbx/admin/modules/visualplan

# Create directories
RUN mkdir -p \
	/var/lib/asterisk/bin/backup \
	/var/log/asterisk \
	/var/www/html/freepbx/admin/assets/ \
	/var/www/html/freepbx/admin/assets/less/cache \
	/var/www/html/freepbx/admin/brand/ \
	/var/www/html/freepbx/admin/modules/asteriskinfo/assets/less/cache \
	/var/www/html/freepbx/admin/modules/backup/assets/less/cache \
	/var/www/html/freepbx/admin/modules/blacklist/assets/less/cache \
	/var/www/html/freepbx/admin/modules/bulkhandler/assets/less/cache \
	/var/www/html/freepbx/admin/modules/calendar/assets/less/cache \
	/var/www/html/freepbx/admin/modules/cdr/assets/less/cache \
	/var/www/html/freepbx/admin/modules/cdr/ucp/assets/less/cache \
	/var/www/html/freepbx/admin/modules/cel/assets/less/cache \
	/var/www/html/freepbx/admin/modules/cel/ucp/assets/less/cache \
	/var/www/html/freepbx/admin/modules/certman/assets/less/cache \
	/var/www/html/freepbx/admin/modules/conferences/assets/less/cache \
	/var/www/html/freepbx/admin/modules/core/assets/less/cache \
	/var/www/html/freepbx/admin/modules/core/assets/less/ampusers/cache \
	/var/www/html/freepbx/admin/modules/core/assets/less/devices/cache \
	/var/www/html/freepbx/admin/modules/core/assets/less/did/cache \
	/var/www/html/freepbx/admin/modules/core/assets/less/extensions/cache \
	/var/www/html/freepbx/admin/modules/core/assets/less/routing/cache \
	/var/www/html/freepbx/admin/modules/core/assets/less/trunks/cache \
	/var/www/html/freepbx/admin/modules/core/assets/less/users/cache \
	/var/www/html/freepbx/admin/modules/core/logs \
	/var/www/html/freepbx/admin/modules/customappsreg/assets/less/cache \
	/var/www/html/freepbx/admin/modules/customappsreg/assets/less/customdests/cache \
	/var/www/html/freepbx/admin/modules/customappsreg/assets/less/customextens/cache \
	/var/www/html/freepbx/admin/modules/dashboard/assets/less/cache \
	/var/www/html/freepbx/admin/modules/featurecodeadmin/assets/less/cache \
	/var/www/html/freepbx/admin/modules/filestore/assets/less/cache \
	/var/www/html/freepbx/admin/modules/ivr/assets/less/cache \
	/var/www/html/freepbx/admin/modules/music/assets/less/cache \
	/var/www/html/freepbx/admin/modules/pm2/node/logs \
	/var/www/html/freepbx/admin/modules/pm2/node/node_modules \
	/var/www/html/freepbx/admin/modules/queueprio/assets/less/cache \
	/var/www/html/freepbx/admin/modules/recordings/assets/less/cache \
	/var/www/html/freepbx/admin/modules/soundlang/assets/less/cache \
	/var/www/html/freepbx/admin/modules/userman/assets/less/cache \
	/var/www/html/freepbx/admin/modules/vmblast/assets/less/cache \
	/var/www/html/freepbx/admin/modules/voicemail/assets/less/cache \
	/var/www/html/freepbx/admin/modules/voicemail/ucp/assets/less/cache \
	/var/www/html/freepbx/admin/images/ \
	/initdb.d

# Fix permissions
RUN chown -R asterisk:asterisk \
	/etc/phonebook/sources.d/ \
	/var/log/asterisk \
	/var/lib/asterisk/.gnupg \
	/var/lib/asterisk/agi-bin \
	/var/lib/asterisk/playback \
	/var/lib/asterisk/bin/backup \
	/var/run/asterisk/ \
	/var/run/nethvoice/ \
	/var/www/html/freepbx/admin/assets/ \
	/var/www/html/freepbx/admin/assets/less/cache \
	/var/www/html/freepbx/admin/images/ \
	/var/www/html/freepbx/admin/modules/core/logs \
	/var/www/html/freepbx/admin/modules/pm2/node/logs \
	/var/www/html/freepbx/admin/modules/pm2/node/node_modules \
	/var/www/html/freepbx/admin/modules/*/assets/less/cache \
	/var/www/html/freepbx/admin/modules/*/ucp/assets/less/cache \
	/var/www/html/freepbx/admin/modules/*/assets/less/*/cache

RUN chown asterisk:asterisk \
	/var/lib/asterisk \
	/var/lib/asterisk/bin \
	/var/www/html/freepbx/admin/assets/js/

# Link visualplan directory to module
RUN ln -s /var/www/html/freepbx/admin/modules/visualplan/htdocs /var/www/html/freepbx/visualplan

# Link all mudule assets directories
RUN for asset in $(find /var/www/html/freepbx/admin/modules/ -type d -name assets); do \
	module=$(echo $asset | cut -d'/' -f8); \
	ln -s $asset /var/www/html/freepbx/admin/assets/$module; \
done

# Replace FreepBX cron implementation with noop
COPY var/www/html/freepbx/admin/libraries/BMO/Cron.class.php /var/www/html/freepbx/admin/libraries/BMO/Cron.class.php

# Add branding
COPY var/www/html/freepbx/admin/brand/* /var/www/html/freepbx/admin/brand/

RUN ln -sf /var/lib/asterisk/bin/fwconsole /usr/bin/fwconsole

RUN pip install mysql.connector asterisk-ami configparser


# Use PHP development ini configuration and enable logging on syslog
COPY usr/local/etc/php/php.ini /usr/local/etc/php/php.ini

# Install php additional modules
RUN docker-php-source extract && \
	docker-php-ext-configure pdo_mysql && docker-php-ext-install pdo_mysql && \
	docker-php-ext-configure gettext && docker-php-ext-install gettext && \
	ln -s /usr/lib/x86_64-linux-gnu/libldap.so /usr/lib/libldap.so && docker-php-ext-configure ldap && docker-php-ext-install ldap && \
	docker-php-ext-configure sysvsem && docker-php-ext-install sysvsem && \
	docker-php-ext-configure pdo_odbc --with-pdo-odbc=unixODBC,/usr && docker-php-ext-install pdo_odbc && \
	docker-php-source delete

# Install nethvoice-wizard-restapi and nethvoice-wizard-ui
COPY var/www/html/freepbx/rest /var/www/html/freepbx/rest
COPY wizard-ui /tmp/wizard
RUN cd /var/www/html/freepbx/rest/ && \
	curl -s https://getcomposer.org/installer | php && \
	COMPOSER_ALLOW_SUPERUSER=1 php composer.phar install --no-dev && \
	rm -fr README.md composer.json composer.lock composer.phar test && \
	cd /tmp/wizard && \
	npx -y -p npm@6 npm install yarn && node_modules/yarn/bin/yarn install && node_modules/grunt-cli/bin/grunt build && \
	mkdir -p /var/www/html/freepbx/wizard && \
	cp -r dist/* /var/www/html/freepbx/wizard/ && \
	rm -fr /tmp/wizard

# enable apache rewrite module
RUN a2enmod rewrite proxy*

# Clean apt files
RUN apt-get clean autoclean && apt-get autoremove --yes && rm -rf /var/lib/{apt,dpkg,cache,log}/* && touch /var/lib/dpkg/status

# Rotate logs hourly
RUN mv /etc/cron.daily/logrotate /etc/cron.hourly/logrotate

# Install centralized phonebook update script and CSV upload path
RUN mkdir -p /usr/share/phonebooks/ /var/lib/nethvoice/phonebook/uploads && \
	chown asterisk:asterisk /var/lib/nethvoice/phonebook/uploads && \
	curl -L https://github.com/nethesis/nethserver-phonebook-mysql/archive/refs/heads/ns8.tar.gz -o - | tar xzp --strip-component=5 -C /usr/share/phonebooks/ nethserver-phonebook-mysql-ns8/root/usr/share/phonebooks

# Overwrite Debian default vim mouse policy
RUN echo "source \$VIMRUNTIME/defaults.vim\nset mouse-=a" >> /root/.vimrc

RUN ln -sf /usr/bin/s-nail /usr/local/bin/sendmail

COPY etc/apache2/sites-enabled/000-default.conf /etc/apache2/sites-enabled/000-default.conf
COPY etc/supervisor/conf.d/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY freepbx_init.sh /freepbx_init.sh
COPY etc/amportal.conf /etc
COPY initdb.d/initdb.php /initdb.d/
COPY initdb.d/migration.php /initdb.d/
COPY usr/src/nethvoice/samples/* /usr/src/nethvoice/samples/
COPY configure_users.php /
COPY entrypoint.sh /entrypoint
CMD ["/usr/bin/supervisord"]
ENTRYPOINT ["/entrypoint"]
