#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

rdb = agent.redis_connect(privileged=True)

# Find default proxy  instance for current node
proxy_id = agent.resolve_agent_id('nethvoice-proxy@node')
config = {
    "proxy_installed": True if proxy_id is not None else False,
}

json.dump(config, fp=sys.stdout)
